import {
  Armchair,
  Sofa,
  BedDouble,
  BedSingle,
  LampDesk,
  Circle,
  RectangleHorizontal,
  Square,
  BookOpen,
  Archive,
  Files,
  CookingPot,
  Droplets,
  Refrigerator,
  Bath,
  Sprout,
  Lamp,
  Tv,
  Table,
  Table2,
  Flame,
  Boxes,
  RectangleVertical,
  LayoutGrid,
  Waves,
  PackageOpen,
  ShowerHead,
  Droplet,
  StretchHorizontal,
  WashingMachine,
  PanelTop,
  Rows3,
  Shirt,
  Layers,
  ToyBrick,
  Sun,
  Flower2,
  Grid2x2,
  Laptop,
  Monitor,
  Amphora,
  Apple,
  Frame,
  Printer,
  Microwave,
  Zap,
  Coffee,
  Recycle,
  TreePine,
  Umbrella,
  SquareStack,
  Toilet,
  Gamepad2,
  Joystick,
  type LucideIcon,
} from "lucide-react";
import chairBaseUrl from "@/assets/chair-base.png";
import sofaUrl from "@/assets/presets/sofa.png";
import armchairUrl from "@/assets/presets/armchair.png";
import bedUrl from "@/assets/presets/bed.png";
import roundTableUrl from "@/assets/presets/round-table.png";
import plantUrl from "@/assets/presets/plant.png";
import toiletUrl from "@/assets/presets/toilet.png";
import bathtubUrl from "@/assets/presets/bathtub.png";
import stoveUrl from "@/assets/presets/stove.png";
import sinkUrl from "@/assets/presets/sink.png";
import fridgeUrl from "@/assets/presets/fridge.png";
import type { Preset, Item } from "@/types/planner";

export const PRESETS: Preset[] = [
  // ---------------------------------------------------------------------
  // MAIN layer -- freestanding furniture, collides normally (unchanged
  // behavior for every item below unless noted). `h` is the real-world
  // height in cm, used for the 3D view.
  // ---------------------------------------------------------------------

  // Seating
  {
    key: "chair-office",
    category: "seating",
    nameEn: "Office chair",
    nameDe: "Bürostuhl",
    w: 60,
    l: 60,
    h: 85,
    color: "#556270",
    iconUrl: chairBaseUrl,
  },
  {
    key: "armchair",
    category: "seating",
    nameEn: "Armchair",
    nameDe: "Sessel",
    w: 90,
    l: 90,
    h: 80,
    color: "#d97706",
    iconUrl: armchairUrl,
  },
  {
    key: "sofa",
    category: "seating",
    nameEn: "Sofa",
    nameDe: "Sofa",
    w: 220,
    l: 95,
    h: 80,
    color: "#cbd5e1",
    iconUrl: sofaUrl,
  },
  {
    key: "loveseat",
    category: "seating",
    nameEn: "Loveseat",
    nameDe: "Zweisitzer-Sofa",
    w: 150,
    l: 90,
    h: 80,
    color: "#b8c4d0",
  },
  {
    key: "accent-chair",
    category: "seating",
    nameEn: "Accent chair",
    nameDe: "Akzentstuhl",
    w: 70,
    l: 70,
    h: 80,
    color: "#b45309",
  },
  // Sleeping / Bedroom
  {
    key: "bed-double",
    category: "sleeping",
    nameEn: "Double bed",
    nameDe: "Doppelbett",
    w: 160,
    l: 200,
    h: 45,
    color: "#f5f5f5",
    iconUrl: bedUrl,
  },
  {
    key: "bed-single",
    category: "sleeping",
    nameEn: "Single bed",
    nameDe: "Einzelbett",
    w: 90,
    l: 200,
    h: 45,
    color: "#f5f5f5",
    iconUrl: bedUrl,
  },
  {
    key: "nightstand",
    category: "sleeping",
    nameEn: "Nightstand",
    nameDe: "Nachttisch",
    w: 45,
    l: 40,
    h: 55,
    color: "#c9a86a",
  },
  {
    key: "dresser",
    category: "sleeping",
    nameEn: "Dresser",
    nameDe: "Kommode",
    w: 100,
    l: 50,
    h: 85,
    color: "#a9744f",
  },
  {
    key: "vanity-table",
    category: "sleeping",
    nameEn: "Vanity table",
    nameDe: "Schminktisch",
    w: 110,
    l: 45,
    h: 75,
    color: "#d9c2a6",
  },
  {
    key: "vanity-stool",
    category: "sleeping",
    nameEn: "Vanity stool",
    nameDe: "Schminkhocker",
    w: 38,
    l: 38,
    h: 45,
    color: "#e2c9a0",
    shape: "circle",
  },
  {
    key: "mirror-full-length",
    category: "sleeping",
    nameEn: "Full-length mirror",
    nameDe: "Standspiegel",
    w: 45,
    l: 10,
    h: 160,
    color: "#cbd5e1",
  },
  {
    key: "bedside-bench",
    category: "sleeping",
    nameEn: "Bed bench",
    nameDe: "Bettbank",
    w: 100,
    l: 40,
    h: 45,
    color: "#a9744f",
  },
  // Tables
  {
    key: "desk",
    category: "tables",
    nameEn: "Desk",
    nameDe: "Schreibtisch",
    w: 160,
    l: 75,
    h: 75,
    color: "#c28a5e",
  },
  {
    key: "round-table",
    category: "tables",
    nameEn: "Round table",
    nameDe: "Runder Tisch",
    w: 110,
    l: 110,
    h: 75,
    color: "#d4a574",
    iconUrl: roundTableUrl,
    shape: "circle",
  },
  {
    key: "coffee-table",
    category: "tables",
    nameEn: "Coffee table",
    nameDe: "Couchtisch",
    w: 100,
    l: 55,
    h: 45,
    color: "#c28a5e",
  },
  {
    key: "side-table",
    category: "tables",
    nameEn: "Side table",
    nameDe: "Beistelltisch",
    w: 45,
    l: 45,
    h: 55,
    color: "#c9a86a",
  },
  // Storage
  {
    key: "bookshelf",
    category: "storage",
    nameEn: "Bookshelf",
    nameDe: "Bücherregal",
    w: 80,
    l: 30,
    h: 180,
    color: "#a07855",
  },
  {
    key: "wardrobe",
    category: "storage",
    nameEn: "Wardrobe",
    nameDe: "Kleiderschrank",
    w: 150,
    l: 60,
    h: 200,
    color: "#b5835a",
  },
  {
    key: "filing-cabinet",
    category: "storage",
    nameEn: "Filing cabinet",
    nameDe: "Aktenschrank",
    w: 60,
    l: 45,
    h: 120,
    color: "#cfd8dc",
  },
  // Kitchen
  {
    key: "stove",
    category: "kitchen",
    nameEn: "Stove",
    nameDe: "Herd",
    w: 60,
    l: 60,
    h: 90,
    color: "#c0c0c0",
    iconUrl: stoveUrl,
  },
  {
    key: "sink",
    category: "kitchen",
    nameEn: "Sink",
    nameDe: "Spüle",
    w: 60,
    l: 50,
    h: 90,
    color: "#c0c0c0",
    iconUrl: sinkUrl,
  },
  {
    key: "fridge",
    category: "kitchen",
    nameEn: "Fridge",
    nameDe: "Kühlschrank",
    w: 70,
    l: 70,
    h: 180,
    color: "#e8e8e8",
    iconUrl: fridgeUrl,
  },
  {
    key: "kitchen-island",
    category: "kitchen",
    nameEn: "Kitchen island",
    nameDe: "Kochinsel",
    w: 120,
    l: 80,
    h: 90,
    color: "#d4d4d8",
  },
  {
    key: "dishwasher",
    category: "kitchen",
    nameEn: "Dishwasher",
    nameDe: "Spülmaschine",
    w: 60,
    l: 60,
    h: 85,
    color: "#cbd5e1",
  },
  {
    key: "oven",
    category: "kitchen",
    nameEn: "Built-in oven",
    nameDe: "Einbaubackofen",
    w: 60,
    l: 60,
    h: 90,
    color: "#71717a",
  },
  {
    key: "pantry-cabinet",
    category: "kitchen",
    nameEn: "Pantry cabinet",
    nameDe: "Vorratsschrank",
    w: 60,
    l: 60,
    h: 200,
    color: "#b08968",
  },
  {
    key: "kitchen-cart",
    category: "kitchen",
    nameEn: "Kitchen cart",
    nameDe: "Küchenwagen",
    w: 60,
    l: 45,
    h: 85,
    color: "#d6d3d1",
  },
  // Bathroom
  {
    key: "toilet",
    category: "bathroom",
    nameEn: "Toilet",
    nameDe: "Toilette",
    w: 40,
    l: 70,
    h: 75,
    color: "#ffffff",
    iconUrl: toiletUrl,
  },
  {
    key: "bathtub",
    category: "bathroom",
    nameEn: "Bathtub",
    nameDe: "Badewanne",
    w: 80,
    l: 170,
    h: 60,
    color: "#ffffff",
    iconUrl: bathtubUrl,
  },
  {
    key: "shower-stall",
    category: "bathroom",
    nameEn: "Shower stall",
    nameDe: "Dusche",
    w: 90,
    l: 90,
    h: 200,
    color: "#e0f2fe",
  },
  {
    key: "bathroom-sink-vanity",
    category: "bathroom",
    nameEn: "Sink vanity",
    nameDe: "Waschtisch",
    w: 80,
    l: 50,
    h: 85,
    color: "#f1f5f9",
  },
  {
    key: "bathroom-cabinet",
    category: "bathroom",
    nameEn: "Bathroom cabinet",
    nameDe: "Badschrank",
    w: 60,
    l: 35,
    h: 130,
    color: "#e5e7eb",
  },
  {
    key: "towel-rack",
    category: "bathroom",
    nameEn: "Towel rack",
    nameDe: "Handtuchhalter",
    w: 60,
    l: 12,
    h: 90,
    color: "#94a3b8",
  },
  {
    key: "washing-machine",
    category: "bathroom",
    nameEn: "Washing machine",
    nameDe: "Waschmaschine",
    w: 60,
    l: 60,
    h: 85,
    color: "#cbd5e1",
  },
  {
    key: "laundry-basket",
    category: "bathroom",
    nameEn: "Laundry basket",
    nameDe: "Wäschekorb",
    w: 40,
    l: 40,
    h: 50,
    color: "#cbd5e1",
    shape: "circle",
  },
  {
    key: "linen-closet",
    category: "bathroom",
    nameEn: "Linen closet",
    nameDe: "Wäscheschrank",
    w: 60,
    l: 40,
    h: 180,
    color: "#e5e7eb",
  },
  // Decor
  {
    key: "plant",
    category: "decor",
    nameEn: "Plant",
    nameDe: "Pflanze",
    w: 50,
    l: 50,
    h: 80,
    color: "#4ade80",
    iconUrl: plantUrl,
  },
  {
    key: "floor-lamp",
    category: "decor",
    nameEn: "Floor lamp",
    nameDe: "Stehlampe",
    w: 30,
    l: 30,
    h: 160,
    color: "#e8c97c",
  },
  {
    key: "planter-tall",
    category: "decor",
    nameEn: "Tall planter",
    nameDe: "Grosse Pflanze",
    w: 40,
    l: 40,
    h: 90,
    color: "#16a34a",
    shape: "circle",
  },
  // Living room
  {
    key: "tv-stand",
    category: "living",
    nameEn: "TV stand",
    nameDe: "TV-Lowboard",
    w: 160,
    l: 40,
    h: 45,
    color: "#3f3f46",
  },
  {
    key: "recliner",
    category: "living",
    nameEn: "Recliner",
    nameDe: "Relaxsessel",
    w: 85,
    l: 95,
    h: 100,
    color: "#78350f",
  },
  {
    key: "ottoman",
    category: "living",
    nameEn: "Ottoman",
    nameDe: "Sitzhocker",
    w: 55,
    l: 55,
    h: 40,
    color: "#a8a29e",
    shape: "circle",
  },
  {
    key: "console-table",
    category: "living",
    nameEn: "Console table",
    nameDe: "Konsolentisch",
    w: 120,
    l: 35,
    h: 75,
    color: "#b08968",
  },
  {
    key: "fireplace",
    category: "living",
    nameEn: "Fireplace",
    nameDe: "Kamin",
    w: 100,
    l: 40,
    h: 90,
    color: "#57534e",
  },
  {
    key: "bar-cart",
    category: "living",
    nameEn: "Bar cart",
    nameDe: "Barwagen",
    w: 70,
    l: 40,
    h: 85,
    color: "#94a3b8",
  },
  // Dining
  {
    key: "dining-table-rect",
    category: "dining",
    nameEn: "Dining table",
    nameDe: "Esstisch",
    w: 160,
    l: 90,
    h: 75,
    color: "#a9744f",
  },
  {
    key: "dining-table-round",
    category: "dining",
    nameEn: "Round dining table",
    nameDe: "Runder Esstisch",
    w: 120,
    l: 120,
    h: 75,
    color: "#b98a5e",
    shape: "circle",
  },
  {
    key: "dining-chair",
    category: "dining",
    nameEn: "Dining chair",
    nameDe: "Esszimmerstuhl",
    w: 45,
    l: 50,
    h: 90,
    color: "#6b7280",
  },
  {
    key: "sideboard",
    category: "dining",
    nameEn: "Sideboard",
    nameDe: "Sideboard",
    w: 140,
    l: 45,
    h: 85,
    color: "#8b5e3c",
  },
  {
    key: "bar-stool",
    category: "dining",
    nameEn: "Bar stool",
    nameDe: "Barhocker",
    w: 38,
    l: 38,
    h: 75,
    color: "#57534e",
    shape: "circle",
  },
  {
    key: "buffet-hutch",
    category: "dining",
    nameEn: "Buffet hutch",
    nameDe: "Anrichte",
    w: 120,
    l: 40,
    h: 180,
    color: "#7c5a3a",
  },
  {
    key: "dining-bench",
    category: "dining",
    nameEn: "Dining bench",
    nameDe: "Sitzbank",
    w: 140,
    l: 40,
    h: 45,
    color: "#6b7280",
  },
  // Home office
  {
    key: "office-desk-l",
    category: "office",
    nameEn: "L-shaped desk",
    nameDe: "L-Schreibtisch",
    w: 180,
    l: 150,
    h: 75,
    color: "#c28a5e",
  },
  {
    key: "whiteboard",
    category: "office",
    nameEn: "Whiteboard",
    nameDe: "Whiteboard",
    w: 100,
    l: 6,
    h: 100,
    color: "#f8fafc",
  },
  // Entryway / hallway
  {
    key: "shoe-rack",
    category: "entryway",
    nameEn: "Shoe rack",
    nameDe: "Schuhregal",
    w: 80,
    l: 30,
    h: 60,
    color: "#92702e",
  },
  {
    key: "coat-rack",
    category: "entryway",
    nameEn: "Coat rack",
    nameDe: "Garderobenständer",
    w: 40,
    l: 40,
    h: 180,
    color: "#57534e",
    shape: "circle",
  },
  {
    key: "entryway-bench",
    category: "entryway",
    nameEn: "Entryway bench",
    nameDe: "Flurbank",
    w: 90,
    l: 40,
    h: 45,
    color: "#a9744f",
  },
  {
    key: "coat-hooks-wall",
    category: "entryway",
    nameEn: "Wall coat hooks",
    nameDe: "Garderobenhaken",
    w: 60,
    l: 8,
    h: 20,
    color: "#78716c",
  },
  // Kids room
  {
    key: "bunk-bed",
    category: "kids",
    nameEn: "Bunk bed",
    nameDe: "Etagenbett",
    w: 100,
    l: 200,
    h: 170,
    color: "#f5f5f5",
  },
  {
    key: "toy-chest",
    category: "kids",
    nameEn: "Toy chest",
    nameDe: "Spielzeugkiste",
    w: 80,
    l: 45,
    h: 45,
    color: "#f59e0b",
  },
  {
    key: "kids-desk",
    category: "kids",
    nameEn: "Kids desk",
    nameDe: "Kinderschreibtisch",
    w: 90,
    l: 50,
    h: 55,
    color: "#93c5fd",
  },
  {
    key: "kids-chair",
    category: "kids",
    nameEn: "Kids chair",
    nameDe: "Kinderstuhl",
    w: 35,
    l: 35,
    h: 50,
    color: "#fca5a5",
  },
  {
    key: "changing-table",
    category: "kids",
    nameEn: "Changing table",
    nameDe: "Wickeltisch",
    w: 90,
    l: 55,
    h: 95,
    color: "#fbcfe8",
  },
  {
    key: "rocking-chair",
    category: "kids",
    nameEn: "Rocking chair",
    nameDe: "Schaukelstuhl",
    w: 60,
    l: 80,
    h: 90,
    color: "#f9a8d4",
  },
  // Outdoor / balcony
  {
    key: "outdoor-table",
    category: "outdoor",
    nameEn: "Outdoor table",
    nameDe: "Gartentisch",
    w: 90,
    l: 90,
    h: 72,
    color: "#52525b",
    shape: "circle",
  },
  {
    key: "outdoor-chair",
    category: "outdoor",
    nameEn: "Outdoor chair",
    nameDe: "Gartenstuhl",
    w: 50,
    l: 50,
    h: 85,
    color: "#44403c",
  },
  {
    key: "sun-lounger",
    category: "outdoor",
    nameEn: "Sun lounger",
    nameDe: "Sonnenliege",
    w: 60,
    l: 190,
    h: 35,
    color: "#d4d4d8",
  },
  {
    key: "planter-box",
    category: "outdoor",
    nameEn: "Planter box",
    nameDe: "Pflanzkasten",
    w: 80,
    l: 30,
    h: 40,
    color: "#4d7c0f",
  },
  {
    key: "bbq-grill",
    category: "outdoor",
    nameEn: "BBQ grill",
    nameDe: "Grill",
    w: 60,
    l: 50,
    h: 100,
    color: "#27272a",
  },
  {
    key: "umbrella-stand",
    category: "outdoor",
    nameEn: "Patio umbrella",
    nameDe: "Sonnenschirm",
    w: 30,
    l: 30,
    h: 25,
    color: "#78716c",
    shape: "circle",
  },

  // ---------------------------------------------------------------------
  // UNDER layer -- sit beneath everything else, never collide with
  // anything (see collidesWithOthers in planner-math.ts). Very low `h` so
  // the 3D view renders them flush with the floor instead of as a box.
  // ---------------------------------------------------------------------
  {
    key: "rug",
    category: "decor",
    nameEn: "Rug",
    nameDe: "Teppich",
    w: 200,
    l: 140,
    h: 0.5,
    color: "#b7806f",
    layer: "under",
  },
  {
    key: "rug-round",
    category: "decor",
    nameEn: "Round rug",
    nameDe: "Runder Teppich",
    w: 160,
    l: 160,
    h: 0.5,
    color: "#c99383",
    layer: "under",
    shape: "circle",
  },
  {
    key: "rug-small",
    category: "decor",
    nameEn: "Small rug",
    nameDe: "Kleiner Teppich",
    w: 90,
    l: 60,
    h: 0.5,
    color: "#a8917e",
    layer: "under",
  },
  {
    key: "doormat",
    category: "entryway",
    nameEn: "Doormat",
    nameDe: "Fussmatte",
    w: 60,
    l: 40,
    h: 1,
    color: "#78716c",
    layer: "under",
  },
  {
    key: "floor-mat-kitchen",
    category: "kitchen",
    nameEn: "Kitchen floor mat",
    nameDe: "Küchenläufer",
    w: 80,
    l: 50,
    h: 0.8,
    color: "#94a3b8",
    layer: "under",
  },
  {
    key: "play-mat",
    category: "kids",
    nameEn: "Play mat",
    nameDe: "Spielmatte",
    w: 150,
    l: 150,
    h: 1.5,
    color: "#86efac",
    layer: "under",
  },

  // ---------------------------------------------------------------------
  // ON-TOP layer -- meant to be placed visually on a main-layer surface
  // (a desk, table, counter, media console); never collide with anything
  // (see collidesWithOthers in planner-math.ts). `h` is the object's own
  // height -- usually small (lamps, laptops, vases), though a propped-up
  // TV runs taller; the 3D view additionally elevates these above the
  // floor by default (see ON_TOP_DEFAULT_ELEVATION in use-room-planner.ts)
  // so they read as sitting on a surface rather than floating at floor
  // level. Dragging one onto a main item auto-elevates it to that item's
  // top surface (see findOnTopHost in planner-math.ts).
  // ---------------------------------------------------------------------
  {
    key: "desk-lamp",
    category: "office",
    nameEn: "Desk lamp",
    nameDe: "Schreibtischlampe",
    w: 20,
    l: 20,
    h: 40,
    color: "#f4d35e",
    layer: "on-top",
  },
  {
    key: "table-lamp",
    category: "living",
    nameEn: "Table lamp",
    nameDe: "Tischlampe",
    w: 25,
    l: 25,
    h: 45,
    color: "#fbbf24",
    layer: "on-top",
    shape: "circle",
  },
  {
    key: "laptop",
    category: "office",
    nameEn: "Laptop",
    nameDe: "Laptop",
    w: 35,
    l: 25,
    h: 3,
    color: "#52525b",
    layer: "on-top",
  },
  {
    key: "monitor",
    category: "office",
    nameEn: "Monitor",
    nameDe: "Monitor",
    w: 55,
    l: 20,
    h: 40,
    color: "#27272a",
    layer: "on-top",
  },
  {
    key: "printer",
    category: "office",
    nameEn: "Printer",
    nameDe: "Drucker",
    w: 40,
    l: 35,
    h: 20,
    color: "#71717a",
    layer: "on-top",
  },
  {
    key: "books-stack",
    category: "living",
    nameEn: "Stack of books",
    nameDe: "Bücherstapel",
    w: 25,
    l: 20,
    h: 15,
    color: "#7c3f00",
    layer: "on-top",
  },
  {
    key: "tray",
    category: "living",
    nameEn: "Tray",
    nameDe: "Tablett",
    w: 35,
    l: 25,
    h: 3,
    color: "#d6d3d1",
    layer: "on-top",
  },
  {
    key: "vase",
    category: "decor",
    nameEn: "Vase",
    nameDe: "Vase",
    w: 15,
    l: 15,
    h: 25,
    color: "#93c5fd",
    layer: "on-top",
    shape: "circle",
  },
  {
    key: "plant-small",
    category: "decor",
    nameEn: "Small potted plant",
    nameDe: "Kleine Topfpflanze",
    w: 20,
    l: 20,
    h: 30,
    color: "#4ade80",
    layer: "on-top",
    shape: "circle",
  },
  {
    key: "picture-frame",
    category: "decor",
    nameEn: "Picture frame",
    nameDe: "Bilderrahmen",
    w: 15,
    l: 10,
    h: 20,
    color: "#d6d3d1",
    layer: "on-top",
  },
  {
    key: "candle",
    category: "decor",
    nameEn: "Candle",
    nameDe: "Kerze",
    w: 10,
    l: 10,
    h: 12,
    color: "#fef3c7",
    layer: "on-top",
    shape: "circle",
  },
  {
    key: "fruit-bowl",
    category: "kitchen",
    nameEn: "Fruit bowl",
    nameDe: "Obstschale",
    w: 25,
    l: 25,
    h: 12,
    color: "#f97316",
    layer: "on-top",
    shape: "circle",
  },
  {
    key: "microwave",
    category: "kitchen",
    nameEn: "Microwave",
    nameDe: "Mikrowelle",
    w: 45,
    l: 35,
    h: 30,
    color: "#6b7280",
    layer: "on-top",
  },
  {
    key: "toaster",
    category: "kitchen",
    nameEn: "Toaster",
    nameDe: "Toaster",
    w: 25,
    l: 15,
    h: 20,
    color: "#a1a1aa",
    layer: "on-top",
  },
  {
    key: "coffee-maker",
    category: "kitchen",
    nameEn: "Coffee maker",
    nameDe: "Kaffeemaschine",
    w: 20,
    l: 20,
    h: 35,
    color: "#44403c",
    layer: "on-top",
  },
  {
    key: "tv-55",
    category: "living",
    nameEn: '55" TV',
    nameDe: '55" Fernseher',
    w: 122,
    l: 15,
    h: 68,
    color: "#18181b",
    layer: "on-top",
  },
  {
    key: "tv-65",
    category: "living",
    nameEn: '65" TV',
    nameDe: '65" Fernseher',
    w: 144,
    l: 16,
    h: 81,
    color: "#18181b",
    layer: "on-top",
  },
  {
    key: "tv-75",
    category: "living",
    nameEn: '75" TV',
    nameDe: '75" Fernseher',
    w: 166,
    l: 18,
    h: 93,
    color: "#18181b",
    layer: "on-top",
  },
  {
    key: "ps5",
    category: "living",
    nameEn: "PS5 console",
    nameDe: "PS5-Konsole",
    w: 16,
    l: 32,
    h: 38,
    color: "#e8e8ea",
    layer: "on-top",
  },
  {
    key: "switch-2",
    category: "living",
    nameEn: "Nintendo Switch 2",
    nameDe: "Nintendo Switch 2",
    w: 16,
    l: 6,
    h: 12,
    color: "#27272a",
    layer: "on-top",
  },
];

export const PRESET_BY_KEY = Object.fromEntries(PRESETS.map((p) => [p.key, p]));

// Lucide icon per preset key (catalog + item rendering)
export const PRESET_ICON: Record<string, LucideIcon> = {
  "chair-office": Armchair,
  armchair: Armchair,
  sofa: Sofa,
  loveseat: Sofa,
  "accent-chair": Armchair,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  nightstand: Table2,
  dresser: Boxes,
  "vanity-table": Table2,
  "vanity-stool": Circle,
  "mirror-full-length": RectangleVertical,
  "bedside-bench": StretchHorizontal,
  desk: LampDesk,
  "round-table": Circle,
  "coffee-table": RectangleHorizontal,
  "side-table": Square,
  bookshelf: BookOpen,
  wardrobe: Archive,
  "filing-cabinet": Files,
  stove: CookingPot,
  sink: Droplets,
  fridge: Refrigerator,
  "kitchen-island": LayoutGrid,
  dishwasher: Waves,
  oven: Flame,
  "pantry-cabinet": PackageOpen,
  "kitchen-cart": Boxes,
  toilet: Toilet,
  bathtub: Bath,
  "shower-stall": ShowerHead,
  "bathroom-sink-vanity": Droplet,
  "bathroom-cabinet": PackageOpen,
  "towel-rack": StretchHorizontal,
  "washing-machine": WashingMachine,
  "laundry-basket": Recycle,
  "linen-closet": Archive,
  plant: Sprout,
  "floor-lamp": Lamp,
  "planter-tall": TreePine,
  "tv-stand": Tv,
  recliner: Armchair,
  ottoman: Circle,
  "console-table": Table2,
  fireplace: Flame,
  "bar-cart": Boxes,
  "dining-table-rect": Table,
  "dining-table-round": Circle,
  "dining-chair": Armchair,
  sideboard: Boxes,
  "bar-stool": Circle,
  "buffet-hutch": Boxes,
  "dining-bench": StretchHorizontal,
  "office-desk-l": Table2,
  whiteboard: PanelTop,
  "shoe-rack": Rows3,
  "coat-rack": Shirt,
  "entryway-bench": StretchHorizontal,
  "coat-hooks-wall": Shirt,
  "bunk-bed": Layers,
  "toy-chest": ToyBrick,
  "kids-desk": Table2,
  "kids-chair": Armchair,
  "changing-table": Table2,
  "rocking-chair": Armchair,
  "outdoor-table": Circle,
  "outdoor-chair": Armchair,
  "sun-lounger": Sun,
  "planter-box": Flower2,
  "bbq-grill": Flame,
  "umbrella-stand": Umbrella,
  rug: Square,
  "rug-round": Circle,
  "rug-small": Square,
  doormat: Square,
  "floor-mat-kitchen": Square,
  "play-mat": Grid2x2,
  "desk-lamp": LampDesk,
  "table-lamp": Lamp,
  laptop: Laptop,
  monitor: Monitor,
  printer: Printer,
  "books-stack": BookOpen,
  tray: SquareStack,
  vase: Amphora,
  "plant-small": Sprout,
  "picture-frame": Frame,
  candle: Flame,
  "fruit-bowl": Apple,
  microwave: Microwave,
  toaster: Zap,
  "coffee-maker": Coffee,
  "tv-55": Tv,
  "tv-65": Tv,
  "tv-75": Tv,
  ps5: Gamepad2,
  "switch-2": Joystick,
};

export function iconUrlForItem(it: Item): string | undefined {
  if (it.icon && PRESET_BY_KEY[it.icon]) return PRESET_BY_KEY[it.icon].iconUrl;
  // legacy back-compat
  if (it.kind === "chair") return chairBaseUrl;
  return undefined;
}

/**
 * Real-world height (cm) to use for the 3D view when an item doesn't carry
 * its own explicit `height`. The catalog (`PRESETS` above) is the source of
 * truth -- covers every current preset. The switch below only exists as a
 * fallback for items that predate the `h` field (old saved rooms) or that
 * don't match a catalog key at all (custom boxes), so it intentionally
 * keeps the same defaults this function always used for those legacy keys.
 */
export function getDefaultHeight(icon?: string, kind?: string): number {
  if (icon) {
    const presetH = PRESET_BY_KEY[icon]?.h;
    if (presetH !== undefined) return presetH;
  }
  if (kind === "chair") return 80;
  if (!icon) return 75; // default custom box height
  switch (icon) {
    case "chair-office":
      return 85;
    case "armchair":
      return 80;
    case "sofa":
      return 80;
    case "bed-double":
    case "bed-single":
      return 45;
    case "desk":
    case "round-table":
      return 75;
    case "coffee-table":
      return 45;
    case "side-table":
      return 55;
    case "bookshelf":
      return 180;
    case "wardrobe":
      return 200;
    case "filing-cabinet":
      return 120;
    case "stove":
    case "sink":
      return 90;
    case "fridge":
      return 180;
    case "toilet":
      return 75;
    case "bathtub":
      return 60;
    case "plant":
      return 80;
    case "floor-lamp":
      return 160;
    case "rug":
      return 0.5; // flat on floor
    default:
      return 75;
  }
}
