import {
  Armchair,
  Sofa,
  BedDouble,
  BedSingle,
  LampDesk,
  Circle,
  RectangleHorizontal,
  Square,
  BookOpen,
  Archive,
  Files,
  CookingPot,
  Droplets,
  Refrigerator,
  Bath,
  Sprout,
  Lamp,
  Tv,
  Table,
  Table2,
  Flame,
  Boxes,
  RectangleVertical,
  LayoutGrid,
  Waves,
  PackageOpen,
  ShowerHead,
  Droplet,
  StretchHorizontal,
  WashingMachine,
  PanelTop,
  Rows3,
  Rows2,
  Shirt,
  Layers,
  ToyBrick,
  Sun,
  Flower2,
  Grid2x2,
  Laptop,
  Monitor,
  Amphora,
  Apple,
  Frame,
  Printer,
  Microwave,
  Zap,
  Coffee,
  Recycle,
  TreePine,
  Umbrella,
  SquareStack,
  Toilet,
  Gamepad2,
  Joystick,
  Lightbulb,
  LampCeiling,
  LampWallUp,
  Blinds,
  Image,
  PanelsLeftRight,
  SprayCan,
  Wine,
  Blend,
  Router,
  Wind,
  Columns2,
  Presentation,
  Trash2,
  Speaker,
  Keyboard,
  Mouse,
  Radio,
  Package,
  PawPrint,
  Cpu,
  Gamepad,
  TrendingUp,
  Fence,
  Volleyball,
  type LucideIcon,
} from "lucide-react";
import chairBaseUrl from "@/assets/chair-base.png";
import sofaUrl from "@/assets/presets/sofa.png";
import armchairUrl from "@/assets/presets/armchair.png";
import bedUrl from "@/assets/presets/bed.png";
import roundTableUrl from "@/assets/presets/round-table.png";
import plantUrl from "@/assets/presets/plant.png";
import toiletUrl from "@/assets/presets/toilet.png";
import bathtubUrl from "@/assets/presets/bathtub.png";
import stoveUrl from "@/assets/presets/stove.png";
import sinkUrl from "@/assets/presets/sink.png";
import fridgeUrl from "@/assets/presets/fridge.png";
import type { Preset, Item } from "@/types/planner";

export const PRESETS: Preset[] = [
  // ---------------------------------------------------------------------
  // MAIN layer -- freestanding furniture, collides normally (unchanged
  // behavior for every item below unless noted). `h` is the real-world
  // height in cm, used for the 3D view. `material` is an explicit hint for
  // the 3D view's surface treatment (see materialParamsFor in
  // ThreeDView.tsx) -- wood grain, upholstery weave, brushed metal, glossy
  // ceramic, and so on. This used to be *guessed* from keywords in the
  // item's icon key/name, which had real gaps (several wood/fabric/metal
  // pieces fell through to a flat generic material) and at least one
  // outright bug (a "bed" keyword match made bunk-bed render in upholstery
  // fabric); every preset now sets it explicitly.
  // ---------------------------------------------------------------------

  // Seating
  {
    key: "chair-office",
    category: "seating",
    nameEn: "Office chair",
    nameDe: "Bürostuhl",
    w: 60,
    l: 60,
    h: 85,
    color: "#5e7777",
    iconUrl: chairBaseUrl,
    material: "leather",
    kitModel: {
      file: "chairDesk.glb",
      minX: 0,
      minY: 0,
      minZ: -31.43,
      maxX: 33.5,
      maxY: 60.76,
      maxZ: 0,
    },
  },
  {
    key: "armchair",
    category: "seating",
    nameEn: "Armchair",
    nameDe: "Sessel",
    w: 90,
    l: 90,
    h: 80,
    color: "#f15e57",
    iconUrl: armchairUrl,
    material: "fabric",
    kitModel: {
      file: "loungeChairRelax.glb",
      minX: 0,
      minY: 0,
      minZ: -67.47,
      maxX: 49,
      maxY: 63,
      maxZ: 0,
    },
  },
  {
    key: "sofa",
    category: "seating",
    nameEn: "Sofa",
    nameDe: "Sofa",
    w: 220,
    l: 95,
    h: 80,
    color: "#5b84dd",
    iconUrl: sofaUrl,
    material: "fabric",
    kitModel: {
      file: "loungeDesignSofa.glb",
      minX: 0,
      minY: 0,
      minZ: -41,
      maxX: 112,
      maxY: 40,
      maxZ: 0,
    },
  },
  {
    key: "loveseat",
    category: "seating",
    nameEn: "Loveseat",
    nameDe: "Zweisitzer-Sofa",
    w: 150,
    l: 90,
    h: 80,
    color: "#f15e57",
    material: "fabric",
    kitModel: { file: "loungeSofa.glb", minX: 0, minY: 0, minZ: -41, maxX: 98, maxY: 46, maxZ: 0 },
  },
  {
    key: "accent-chair",
    category: "seating",
    nameEn: "Accent chair",
    nameDe: "Akzentstuhl",
    w: 70,
    l: 70,
    h: 80,
    color: "#f15e57",
    material: "fabric",
    kitModel: { file: "loungeChair.glb", minX: 0, minY: 0, minZ: -41, maxX: 49, maxY: 46, maxZ: 0 },
  },
  // Sleeping / Bedroom
  {
    key: "bed-double",
    category: "sleeping",
    nameEn: "Double bed",
    nameDe: "Doppelbett",
    w: 160,
    l: 200,
    h: 45,
    color: "#f8ffff",
    iconUrl: bedUrl,
    material: "fabric",
    kitModel: {
      file: "bedDouble.glb",
      minX: 0,
      minY: 0,
      minZ: -112.5,
      maxX: 95.6,
      maxY: 37.5,
      maxZ: 0,
    },
  },
  {
    key: "bed-single",
    category: "sleeping",
    nameEn: "Single bed",
    nameDe: "Einzelbett",
    w: 90,
    l: 200,
    h: 45,
    color: "#f8ffff",
    iconUrl: bedUrl,
    material: "fabric",
    kitModel: {
      file: "bedSingle.glb",
      minX: 38.5,
      minY: 0,
      minZ: -112.5,
      maxX: 95.6,
      maxY: 37.5,
      maxZ: 0,
    },
  },
  {
    key: "nightstand",
    category: "sleeping",
    nameEn: "Nightstand",
    nameDe: "Nachttisch",
    w: 45,
    l: 40,
    h: 55,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "cabinetBedDrawer.glb",
      minX: -1,
      minY: 0,
      minZ: -20.5,
      maxX: 25.6,
      maxY: 26.32,
      maxZ: 1.23,
    },
  },
  {
    key: "dresser",
    category: "sleeping",
    nameEn: "Dresser",
    nameDe: "Kommode",
    w: 100,
    l: 50,
    h: 85,
    color: "#a9744f",
    material: "wood",
    proceduralModel: { family: "cabinetBox", params: { doorLines: 3 } },
  },
  {
    key: "vanity-table",
    category: "sleeping",
    nameEn: "Vanity table",
    nameDe: "Schminktisch",
    w: 110,
    l: 45,
    h: 75,
    color: "#d9c2a6",
    material: "wood",
    proceduralModel: { family: "legFrame" },
  },
  {
    key: "vanity-stool",
    category: "sleeping",
    nameEn: "Vanity stool",
    nameDe: "Schminkhocker",
    w: 38,
    l: 38,
    h: 45,
    color: "#e2c9a0",
    shape: "circle",
    material: "fabric",
    proceduralModel: { family: "legFrame", params: { roundTop: true, legFrac: 0.1 } },
  },
  {
    // Was 160cm -- real floor mirrors run closer to 170-180cm; bumped so it
    // reads correctly against a person's height in the 3D view. Also now an
    // explicit "glass" material (a genuinely reflective-looking surface)
    // instead of the flat generic default it fell through to before.
    key: "mirror-full-length",
    category: "sleeping",
    nameEn: "Full-length mirror",
    nameDe: "Standspiegel",
    w: 45,
    l: 10,
    h: 175,
    color: "#cbd5e1",
    material: "glass",
  },
  {
    key: "bedside-bench",
    category: "sleeping",
    nameEn: "Bed bench",
    nameDe: "Bettbank",
    w: 100,
    l: 40,
    h: 45,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "benchCushionLow.glb",
      minX: -1,
      minY: 0,
      minZ: -21,
      maxX: 41,
      maxY: 20,
      maxZ: 1,
    },
  },
  // Tables
  {
    key: "desk",
    category: "tables",
    nameEn: "Desk",
    nameDe: "Schreibtisch",
    w: 160,
    l: 75,
    h: 75,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "desk.glb",
      minX: -1,
      minY: 0,
      minZ: -38,
      maxX: 72.45,
      maxY: 38.44,
      maxZ: 1.23,
    },
  },
  {
    key: "round-table",
    category: "tables",
    nameEn: "Round table",
    nameDe: "Runder Tisch",
    w: 110,
    l: 110,
    h: 75,
    color: "#e59964",
    iconUrl: roundTableUrl,
    shape: "circle",
    material: "wood",
    kitModel: {
      file: "tableRound.glb",
      minX: 0,
      minY: -27,
      minZ: -80,
      maxX: 69.28,
      maxY: 9.67,
      maxZ: 0,
    },
  },
  {
    key: "coffee-table",
    category: "tables",
    nameEn: "Coffee table",
    nameDe: "Couchtisch",
    w: 100,
    l: 55,
    h: 45,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "tableCoffee.glb",
      minX: -46.1,
      minY: 0,
      minZ: -30,
      maxX: 20,
      maxY: 23,
      maxZ: 10,
    },
  },
  {
    key: "side-table",
    category: "tables",
    nameEn: "Side table",
    nameDe: "Beistelltisch",
    w: 45,
    l: 45,
    h: 55,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "sideTable.glb",
      minX: -1,
      minY: 0,
      minZ: -21,
      maxX: 52.45,
      maxY: 38.44,
      maxZ: 1,
    },
  },
  // Storage
  {
    key: "bookshelf",
    category: "storage",
    nameEn: "Bookshelf",
    nameDe: "Bücherregal",
    w: 80,
    l: 30,
    h: 180,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "bookcaseOpen.glb",
      minX: 0,
      minY: 0,
      minZ: -25,
      maxX: 40,
      maxY: 88,
      maxZ: 0,
    },
  },
  {
    key: "wardrobe",
    category: "storage",
    nameEn: "Wardrobe",
    nameDe: "Kleiderschrank",
    w: 150,
    l: 60,
    h: 200,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "bookcaseClosedWide.glb",
      minX: 0,
      minY: 0,
      minZ: -25,
      maxX: 80,
      maxY: 79,
      maxZ: 0,
    },
  },
  {
    // Open cube-grid shelving (KALLAX/EKET/TROFAST-style) -- a proceduralModel
    // rather than a kitModel deliberately, since these product lines' real
    // dimensions span a much wider range (a 42cm-wide KALLAX 1x2 up to a
    // 147cm-wide 4x4) than any single Kenney kit-model envelope tolerates;
    // cubeGridShelf reads the item's own current w/h and always renders an
    // exactly-fitting grid, so it never falls back to a plain flat box the
    // way an out-of-envelope kitModel item would.
    key: "cube-shelf",
    category: "storage",
    nameEn: "Cube Storage Shelf",
    nameDe: "Würfelregal",
    w: 77,
    l: 39,
    h: 147,
    color: "#ffffff",
    material: "wood",
    proceduralModel: { family: "cubeGridShelf" },
  },
  {
    // Open bookcase (BILLY/IVAR/HEMNES-style) -- side panels + evenly spaced
    // shelf boards, open front. See "cube-shelf" above for why this is a
    // proceduralModel: BILLY alone ranges from a 106cm-tall low unit to a
    // 202cm tall one, well past one kitModel's usable stretch envelope.
    key: "ladder-bookcase",
    category: "storage",
    nameEn: "Ladder Bookcase",
    nameDe: "Standregal",
    w: 80,
    l: 28,
    h: 202,
    color: "#ffffff",
    material: "wood",
    proceduralModel: { family: "ladderShelf" },
  },
  {
    // Tall hinged-door wardrobe (PAX/BRIMNES-style) -- door-seam lines and
    // handle accents split the front into leaves whose count is derived
    // from width, so a 78cm 2-door BRIMNES and a 150cm 3-door PAX both read
    // correctly from the one generator. See "cube-shelf" above for why this
    // is a proceduralModel rather than a kitModel.
    key: "door-wardrobe",
    category: "storage",
    nameEn: "Door Wardrobe",
    nameDe: "Kleiderschrank mit Türen",
    w: 100,
    l: 60,
    h: 220, // generic default kept within this app's freestanding-furniture height ceiling; the IKEA PAX entry (up to 236cm) sets its own real h and isn't bound by this preset's default

    color: "#ffffff",
    material: "wood",
    proceduralModel: { family: "doorWardrobe" },
  },
  {
    // Low storage cabinet on short feet (BESTÅ/sideboard-style) -- reuses
    // cabinetBox's existing door-line accents with its `legs` option turned
    // on, rather than a bespoke family, since a legged low cabinet is
    // otherwise identical to the plain cabinetBox silhouette.
    key: "leg-cabinet",
    category: "storage",
    nameEn: "Low Cabinet",
    nameDe: "Sideboard",
    w: 140,
    l: 42,
    h: 74,
    color: "#2b2523",
    material: "wood",
    proceduralModel: { family: "cabinetBox", params: { doorLines: 2, legs: true } },
  },
  {
    // Was rendering in wood grain regardless of its gray color -- the old
    // keyword logic's metal-override check compared against a hardcoded
    // hex the preset's own default color never matched, so the "metal"
    // branch was dead code in practice. An explicit material fixes it.
    key: "filing-cabinet",
    category: "storage",
    nameEn: "Filing cabinet",
    nameDe: "Aktenschrank",
    w: 60,
    l: 45,
    h: 120,
    color: "#cfd8dc",
    material: "metal",
    proceduralModel: { family: "cabinetBox", params: { doorLines: 2 } },
  },
  // Kitchen
  {
    key: "stove",
    category: "kitchen",
    nameEn: "Stove",
    nameDe: "Herd",
    w: 60,
    l: 60,
    h: 90,
    color: "#bdd2d6",
    iconUrl: stoveUrl,
    material: "metal",
    kitModel: {
      file: "kitchenStoveElectric.glb",
      minX: 0,
      minY: 0,
      minZ: -45,
      maxX: 43,
      maxY: 45,
      maxZ: 0,
    },
  },
  {
    key: "sink",
    category: "kitchen",
    nameEn: "Sink",
    nameDe: "Spüle",
    w: 60,
    l: 50,
    h: 90,
    color: "#bdd2d6",
    iconUrl: sinkUrl,
    material: "metal",
    kitModel: { file: "kitchenSink.glb", minX: 0, minY: 0, minZ: -45, maxX: 43, maxY: 49, maxZ: 0 },
  },
  {
    key: "fridge",
    category: "kitchen",
    nameEn: "Fridge",
    nameDe: "Kühlschrank",
    w: 70,
    l: 70,
    h: 180,
    color: "#effaf4",
    iconUrl: fridgeUrl,
    material: "metal",
    kitModel: {
      file: "kitchenFridgeLarge.glb",
      minX: 0,
      minY: 0,
      minZ: -34.19,
      maxX: 52,
      maxY: 92,
      maxZ: 6.36,
    },
  },
  {
    key: "kitchen-island",
    category: "kitchen",
    nameEn: "Kitchen island",
    nameDe: "Kochinsel",
    w: 120,
    l: 80,
    h: 90,
    color: "#d4d4d8",
    material: "stone",
    proceduralModel: { family: "cabinetBox", params: { doorLines: 1, topOverhang: true } },
  },
  {
    key: "dishwasher",
    category: "kitchen",
    nameEn: "Dishwasher",
    nameDe: "Spülmaschine",
    w: 60,
    l: 60,
    h: 85,
    color: "#cbd5e1",
    material: "metal",
    proceduralModel: { family: "panelAccentBox" },
  },
  {
    key: "oven",
    category: "kitchen",
    nameEn: "Built-in oven",
    nameDe: "Einbaubackofen",
    w: 60,
    l: 60,
    h: 90,
    color: "#71717a",
    material: "metal",
    proceduralModel: { family: "panelAccentBox" },
  },
  {
    key: "pantry-cabinet",
    category: "kitchen",
    nameEn: "Pantry cabinet",
    nameDe: "Vorratsschrank",
    w: 60,
    l: 60,
    h: 200,
    color: "#b08968",
    material: "wood",
    proceduralModel: { family: "cabinetBox", params: { doorLines: 1 } },
  },
  {
    key: "kitchen-cart",
    category: "kitchen",
    nameEn: "Kitchen cart",
    nameDe: "Küchenwagen",
    w: 60,
    l: 45,
    h: 85,
    color: "#d6d3d1",
    material: "wood",
    proceduralModel: { family: "legFrame", params: { shelfFrac: 0.3 } },
  },
  {
    key: "trash-bin",
    category: "kitchen",
    nameEn: "Trash & recycling bin",
    nameDe: "Mülleimer",
    w: 40,
    l: 30,
    h: 65,
    color: "#bdd2d6",
    material: "metal",
    kitModel: {
      file: "trashcan.glb",
      minX: -10.38,
      minY: 0,
      minZ: -11.16,
      maxX: 10.38,
      maxY: 42.79,
      maxZ: 12.25,
    },
  },
  {
    // Same trashcan.glb as "trash-bin", just scaled to a smaller default --
    // the kit-model envelope check (kit-models.ts) compares against each
    // preset's OWN default size, so reusing one glb across differently
    // sized presets is fine.
    key: "trash-bin-small",
    category: "kitchen",
    nameEn: "Small trash bin",
    nameDe: "Kleiner Mülleimer",
    w: 26,
    l: 22,
    h: 42,
    color: "#bdd2d6",
    material: "metal",
    kitModel: {
      file: "trashcan.glb",
      minX: -10.38,
      minY: 0,
      minZ: -11.16,
      maxX: 10.38,
      maxY: 42.79,
      maxZ: 12.25,
    },
  },
  {
    key: "trash-bin-large",
    category: "kitchen",
    nameEn: "Large trash bin",
    nameDe: "Großer Mülleimer",
    w: 50,
    l: 40,
    h: 80,
    color: "#bdd2d6",
    material: "metal",
    kitModel: {
      file: "trashcan.glb",
      minX: -10.38,
      minY: 0,
      minZ: -11.16,
      maxX: 10.38,
      maxY: 42.79,
      maxZ: 12.25,
    },
  },
  {
    // Reuses the same open-crate model as "cardboard-box-open" (decor
    // category) -- a real open box/crate is a common stand-in for a
    // household recycling bin, and kit models are already shared across
    // multiple presets elsewhere in this catalog.
    key: "recycling-box",
    category: "kitchen",
    nameEn: "Recycling box",
    nameDe: "Recyclingbox",
    w: 45,
    l: 35,
    h: 35,
    color: "#86efac",
    material: "plastic",
    kitModel: {
      file: "cardboardBoxOpen.glb",
      minX: -7.97,
      minY: 0,
      minZ: -21.25,
      maxX: 29.22,
      maxY: 28.1,
      maxZ: 0,
    },
  },
  {
    key: "wine-fridge",
    category: "kitchen",
    nameEn: "Wine fridge",
    nameDe: "Weinkühlschrank",
    w: 45,
    l: 55,
    h: 82,
    color: "#effaf4",
    material: "glass",
    kitModel: {
      file: "kitchenFridgeSmall.glb",
      minX: 0,
      minY: 0,
      minZ: -28.19,
      maxX: 43,
      maxY: 60.02,
      maxZ: 1,
    },
  },
  // Bathroom
  {
    key: "toilet",
    category: "bathroom",
    nameEn: "Toilet",
    nameDe: "Toilette",
    w: 40,
    l: 70,
    h: 75,
    color: "#f8ffff",
    iconUrl: toiletUrl,
    material: "ceramic",
    // Corrected 2026-07: recorded bounding box was ~2-3x too large on every
    // axis vs. the actual toilet.glb mesh, same class of bug as laptop's.
    kitModel: {
      file: "toilet.glb",
      minX: 0,
      minY: 0,
      minZ: 0,
      maxX: 31.26,
      maxY: 45.1,
      maxZ: 47.72,
    },
  },
  {
    key: "bathtub",
    category: "bathroom",
    nameEn: "Bathtub",
    nameDe: "Badewanne",
    // Swapped from the old procedural shape's 80x170 (long axis as
    // "length") to 170x75 (long axis as "width") to match bathtub.glb's
    // own native proportions -- also the physically correct way a tub
    // actually sits (long side flush against a wall, short side
    // projecting into the room).
    w: 170,
    l: 75,
    h: 60,
    color: "#f8ffff",
    iconUrl: bathtubUrl,
    material: "ceramic",
    kitModel: {
      file: "bathtub.glb",
      minX: 0,
      minY: 0,
      minZ: -56,
      maxX: 119,
      maxY: 42,
      maxZ: 0,
    },
  },
  {
    key: "shower-stall",
    category: "bathroom",
    nameEn: "Shower stall",
    nameDe: "Dusche",
    w: 90,
    l: 90,
    h: 200,
    color: "#b2d3c4",
    material: "glass",
    kitModel: {
      file: "shower.glb",
      minX: -56.18,
      minY: 0,
      minZ: -56.18,
      maxX: 0,
      maxY: 109.4,
      maxZ: 2,
    },
  },
  {
    key: "bathroom-sink-vanity",
    category: "bathroom",
    nameEn: "Sink vanity",
    nameDe: "Waschtisch",
    w: 80,
    l: 50,
    h: 85,
    color: "#f8ffff",
    material: "stone",
    kitModel: {
      file: "bathroomSinkSquare.glb",
      minX: 0,
      minY: 5.68,
      minZ: -45,
      maxX: 43,
      maxY: 63.68,
      maxZ: -15,
    },
  },
  {
    key: "bathroom-cabinet",
    category: "bathroom",
    nameEn: "Bathroom cabinet",
    nameDe: "Badschrank",
    w: 60,
    l: 35,
    h: 130,
    color: "#e5e7eb",
    material: "wood",
    proceduralModel: { family: "cabinetBox", params: { doorLines: 2 } },
  },
  {
    // Retagged from "main" to "wall": a towel rack is mounted on the wall,
    // not sitting on the floor, and previously had no elevation at all --
    // it would drop in at floor level as a small awkward box (and
    // needlessly block floor space for other furniture, since "main"
    // items collide). "wall" layer items never collide (see
    // collidesWithOthers in planner-math.ts) and keep their own fixed
    // mount height regardless of what's dragged near them (see ItemLayer
    // in types/planner.ts).
    key: "towel-rack",
    category: "bathroom",
    nameEn: "Towel rack",
    nameDe: "Handtuchhalter",
    w: 60,
    l: 12,
    h: 90,
    color: "#94a3b8",
    layer: "wall",
    elevation: 90,
    material: "metal",
  },
  {
    key: "washing-machine",
    category: "bathroom",
    nameEn: "Washing machine",
    nameDe: "Waschmaschine",
    w: 60,
    l: 60,
    h: 85,
    color: "#effaf4",
    material: "metal",
    kitModel: { file: "washer.glb", minX: 0, minY: 0, minZ: -35, maxX: 39, maxY: 47, maxZ: 4 },
  },
  {
    key: "laundry-basket",
    category: "bathroom",
    nameEn: "Laundry basket",
    nameDe: "Wäschekorb",
    w: 40,
    l: 40,
    h: 50,
    color: "#cbd5e1",
    shape: "circle",
    material: "fabric",
  },
  {
    key: "linen-closet",
    category: "bathroom",
    nameEn: "Linen closet",
    nameDe: "Wäscheschrank",
    w: 60,
    l: 40,
    h: 180,
    color: "#e5e7eb",
    material: "wood",
    proceduralModel: { family: "cabinetBox", params: { doorLines: 2 } },
  },
  {
    key: "bidet",
    category: "bathroom",
    nameEn: "Bidet",
    nameDe: "Bidet",
    w: 40,
    l: 60,
    h: 40,
    color: "#ffffff",
    material: "ceramic",
    proceduralModel: { family: "pedestalFixture", params: { hasTank: false } },
  },
  {
    // Oval/rounded footprint via the existing circle-shape treatment (an
    // inscribed ellipse) -- a nicer match for a real freestanding soaking
    // tub than a hard rectangle, and a distinct premium alternative to the
    // built-in "bathtub" above.
    key: "soaking-tub",
    category: "bathroom",
    nameEn: "Freestanding soaking tub",
    nameDe: "Freistehende Badewanne",
    w: 75,
    l: 170,
    h: 65,
    color: "#ffffff",
    shape: "circle",
    material: "ceramic",
    proceduralModel: { family: "tubShape", params: { round: true } },
  },
  // Decor
  {
    key: "plant",
    category: "decor",
    nameEn: "Plant",
    nameDe: "Pflanze",
    w: 50,
    l: 50,
    h: 80,
    color: "#2ed193",
    iconUrl: plantUrl,
    material: "plant",
    kitModel: {
      file: "pottedPlant.glb",
      minX: -10.6,
      minY: 0,
      minZ: -12.07,
      maxX: 10.6,
      maxY: 65.4,
      maxZ: 12.07,
    },
  },
  {
    key: "floor-lamp",
    category: "decor",
    nameEn: "Floor lamp",
    nameDe: "Stehlampe",
    w: 30,
    l: 30,
    h: 160,
    color: "#bdd2d6",
    material: "metal",
    isLightSource: true,
    kitModel: {
      file: "lampRoundFloor.glb",
      minX: -1.6,
      minY: 0,
      minZ: -14.78,
      maxX: 13.6,
      maxY: 86,
      maxZ: 2.78,
    },
  },
  {
    key: "planter-tall",
    category: "decor",
    nameEn: "Tall planter",
    nameDe: "Grosse Pflanze",
    w: 40,
    l: 40,
    h: 90,
    color: "#2ed193",
    shape: "circle",
    material: "plant",
    kitModel: {
      file: "pottedPlant.glb",
      minX: -10.6,
      minY: 0,
      minZ: -12.07,
      maxX: 10.6,
      maxY: 65.4,
      maxZ: 12.07,
    },
  },
  {
    key: "curtains",
    category: "decor",
    nameEn: "Curtains",
    nameDe: "Vorhänge",
    w: 140,
    l: 8,
    h: 220,
    color: "#7c6a58",
    layer: "wall",
    elevation: 0,
    material: "fabric",
  },
  {
    key: "blinds",
    category: "decor",
    nameEn: "Window blinds",
    nameDe: "Jalousien",
    w: 120,
    l: 4,
    h: 130,
    color: "#e5e7eb",
    layer: "wall",
    elevation: 100,
    material: "plastic",
  },
  {
    key: "canvas-art-large",
    category: "decor",
    nameEn: "Canvas art print",
    nameDe: "Leinwandbild",
    w: 100,
    l: 4,
    h: 70,
    color: "#3b5169",
    layer: "wall",
    elevation: 130,
    material: "fabric",
  },
  // Living room
  {
    key: "tv-stand",
    category: "living",
    nameEn: "TV stand",
    nameDe: "TV-Lowboard",
    w: 160,
    l: 40,
    h: 45,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "cabinetTelevision.glb",
      minX: 0,
      minY: 0,
      minZ: -25,
      maxX: 80,
      maxY: 31,
      maxZ: 0,
    },
  },
  {
    key: "recliner",
    category: "living",
    nameEn: "Recliner",
    nameDe: "Relaxsessel",
    w: 85,
    l: 95,
    h: 100,
    color: "#f15e57",
    material: "leather",
    kitModel: {
      file: "loungeChairRelax.glb",
      minX: 0,
      minY: 0,
      minZ: -67.47,
      maxX: 49,
      maxY: 63,
      maxZ: 0,
    },
  },
  {
    key: "ottoman",
    category: "living",
    nameEn: "Ottoman",
    nameDe: "Sitzhocker",
    w: 55,
    l: 55,
    h: 40,
    color: "#e59964",
    shape: "circle",
    material: "fabric",
    kitModel: {
      file: "loungeSofaOttoman.glb",
      minX: 47,
      minY: 0,
      minZ: -4,
      maxX: 90.98,
      maxY: 23,
      maxZ: 41,
    },
  },
  {
    key: "console-table",
    category: "living",
    nameEn: "Console table",
    nameDe: "Konsolentisch",
    w: 120,
    l: 35,
    h: 75,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "sideTable.glb",
      minX: -1,
      minY: 0,
      minZ: -21,
      maxX: 52.45,
      maxY: 38.44,
      maxZ: 1,
    },
  },
  {
    key: "fireplace",
    category: "living",
    nameEn: "Fireplace",
    nameDe: "Kamin",
    w: 100,
    l: 40,
    h: 90,
    color: "#57534e",
    material: "stone",
    proceduralModel: {
      family: "panelAccentBox",
      params: { panelWFrac: 0.5, panelHFrac: 0.45, colorOffset: -0.3 },
    },
  },
  {
    key: "bar-cart",
    category: "living",
    nameEn: "Bar cart",
    nameDe: "Barwagen",
    w: 70,
    l: 40,
    h: 85,
    color: "#94a3b8",
    material: "metal",
    proceduralModel: { family: "legFrame", params: { shelfFrac: 0.35 } },
  },
  {
    key: "pendant-light",
    category: "living",
    nameEn: "Pendant light",
    nameDe: "Pendelleuchte",
    w: 30,
    l: 30,
    h: 35,
    color: "#ffe996",
    shape: "circle",
    layer: "wall",
    elevation: 175,
    material: "metal",
    isLightSource: true,
    kitModel: {
      file: "lampSquareCeiling.glb",
      minX: 0,
      minY: 0,
      minZ: -12,
      maxX: 12,
      maxY: 23,
      maxZ: 0,
    },
  },
  // Dining
  {
    key: "dining-table-rect",
    category: "dining",
    nameEn: "Dining table",
    nameDe: "Esstisch",
    w: 160,
    l: 90,
    h: 75,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "table.glb",
      minX: 0,
      minY: 0,
      minZ: -44.74,
      maxX: 84.15,
      maxY: 32.67,
      maxZ: 0,
    },
  },
  {
    key: "dining-table-round",
    category: "dining",
    nameEn: "Round dining table",
    nameDe: "Runder Esstisch",
    w: 120,
    l: 120,
    h: 75,
    color: "#e59964",
    shape: "circle",
    material: "wood",
    kitModel: {
      file: "tableRound.glb",
      minX: 0,
      minY: -27,
      minZ: -80,
      maxX: 69.28,
      maxY: 9.67,
      maxZ: 0,
    },
  },
  {
    key: "dining-chair",
    category: "dining",
    nameEn: "Dining chair",
    nameDe: "Esszimmerstuhl",
    w: 45,
    l: 50,
    h: 90,
    color: "#e59964",
    material: "fabric",
    kitModel: {
      file: "chairCushion.glb",
      minX: 0,
      minY: 0,
      minZ: -20,
      maxX: 20,
      maxY: 46,
      maxZ: 0,
    },
  },
  {
    key: "sideboard",
    category: "dining",
    nameEn: "Sideboard",
    nameDe: "Sideboard",
    w: 140,
    l: 45,
    h: 85,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "bookcaseClosedWide.glb",
      minX: 0,
      minY: 0,
      minZ: -25,
      maxX: 80,
      maxY: 79,
      maxZ: 0,
    },
  },
  {
    key: "bar-stool",
    category: "dining",
    nameEn: "Bar stool",
    nameDe: "Barhocker",
    w: 38,
    l: 38,
    h: 75,
    color: "#e59964",
    shape: "circle",
    material: "leather",
    kitModel: {
      file: "stoolBar.glb",
      minX: 0,
      minY: 0,
      minZ: -22.99,
      maxX: 26.54,
      maxY: 43.5,
      maxZ: 0,
    },
  },
  {
    key: "buffet-hutch",
    category: "dining",
    nameEn: "Buffet hutch",
    nameDe: "Anrichte",
    w: 120,
    l: 40,
    h: 180,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "bookcaseClosedDoors.glb",
      minX: 0,
      minY: 0,
      minZ: -25,
      maxX: 40,
      maxY: 85,
      maxZ: 0,
    },
  },
  {
    key: "dining-bench",
    category: "dining",
    nameEn: "Dining bench",
    nameDe: "Sitzbank",
    w: 140,
    l: 40,
    h: 45,
    color: "#e59964",
    material: "wood",
    kitModel: { file: "bench.glb", minX: 0, minY: 0, minZ: -20, maxX: 40, maxY: 47, maxZ: 0 },
  },
  {
    key: "chandelier-dining",
    category: "dining",
    nameEn: "Dining chandelier",
    nameDe: "Kronleuchter",
    w: 65,
    l: 65,
    h: 55,
    color: "#c9a44c",
    shape: "circle",
    layer: "wall",
    elevation: 170,
    material: "metal",
    isLightSource: true,
    proceduralModel: { family: "poleLamp", params: { mount: "ceiling", shade: "sphereCluster" } },
  },
  // Home office
  {
    key: "office-desk-l",
    category: "office",
    nameEn: "L-shaped desk",
    nameDe: "L-Schreibtisch",
    w: 180,
    l: 150,
    h: 75,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "deskCorner.glb",
      minX: 0,
      minY: 0,
      minZ: -97.45,
      maxX: 97.45,
      maxY: 38.44,
      maxZ: 0,
    },
  },
  {
    key: "whiteboard",
    category: "office",
    nameEn: "Whiteboard",
    nameDe: "Whiteboard",
    w: 100,
    l: 6,
    h: 100,
    color: "#f8fafc",
    material: "ceramic",
  },
  {
    key: "standing-desk",
    category: "office",
    nameEn: "Standing desk",
    nameDe: "Steh-Schreibtisch",
    w: 160,
    l: 75,
    h: 110,
    color: "#d4d4d8",
    material: "metal",
    proceduralModel: { family: "legFrame", params: { legFrac: 0.03 } },
  },
  {
    key: "desk-pedestal",
    category: "office",
    nameEn: "Desk pedestal",
    nameDe: "Rollcontainer",
    w: 40,
    l: 50,
    h: 60,
    color: "#52525b",
    material: "metal",
    proceduralModel: { family: "cabinetBox", params: { doorLines: 1 } },
  },
  {
    key: "office-credenza",
    category: "office",
    nameEn: "Office credenza",
    nameDe: "Büro-Sideboard",
    w: 120,
    l: 45,
    h: 75,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "bookcaseClosedWide.glb",
      minX: 0,
      minY: 0,
      minZ: -25,
      maxX: 80,
      maxY: 79,
      maxZ: 0,
    },
  },
  {
    key: "guest-chair",
    category: "office",
    nameEn: "Guest chair",
    nameDe: "Besucherstuhl",
    w: 55,
    l: 55,
    h: 85,
    color: "#bdd2d6",
    material: "fabric",
    kitModel: {
      file: "chairModernCushion.glb",
      minX: 0,
      minY: 0,
      minZ: -20,
      maxX: 20,
      maxY: 46,
      maxZ: 0,
    },
  },
  {
    key: "room-divider",
    category: "office",
    nameEn: "Room divider screen",
    nameDe: "Raumteiler",
    w: 150,
    l: 3,
    h: 170,
    color: "#94a3b8",
    material: "fabric",
  },
  {
    key: "corkboard",
    category: "office",
    nameEn: "Cork board",
    nameDe: "Pinnwand",
    w: 80,
    l: 4,
    h: 60,
    color: "#c99a6b",
    layer: "wall",
    elevation: 140,
    material: "wood",
  },
  // Entryway / hallway
  {
    key: "shoe-rack",
    category: "entryway",
    nameEn: "Shoe rack",
    nameDe: "Schuhregal",
    w: 80,
    l: 30,
    h: 60,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "bookcaseOpenLow.glb",
      minX: 0,
      minY: 0,
      minZ: -25,
      maxX: 40,
      maxY: 40,
      maxZ: 0,
    },
  },
  {
    key: "coat-rack",
    category: "entryway",
    nameEn: "Coat rack",
    nameDe: "Garderobenständer",
    w: 40,
    l: 40,
    h: 180,
    color: "#e59964",
    shape: "circle",
    material: "metal",
    kitModel: {
      file: "coatRackStanding.glb",
      minX: -13.64,
      minY: 0,
      minZ: -13.64,
      maxX: 13.64,
      maxY: 77,
      maxZ: 13.64,
    },
  },
  {
    key: "entryway-bench",
    category: "entryway",
    nameEn: "Entryway bench",
    nameDe: "Flurbank",
    w: 90,
    l: 40,
    h: 45,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "benchCushion.glb",
      minX: 0,
      minY: 0,
      minZ: -20,
      maxX: 40,
      maxY: 46,
      maxZ: 0,
    },
  },
  {
    // Retagged from "main" to "wall" for the same reason as towel-rack
    // above: a row of coat hooks is mounted on the wall at roughly
    // shoulder/coat height, not sitting on the floor.
    key: "coat-hooks-wall",
    category: "entryway",
    nameEn: "Wall coat hooks",
    nameDe: "Garderobenhaken",
    w: 60,
    l: 8,
    h: 20,
    color: "#5e7777",
    layer: "wall",
    elevation: 160,
    material: "metal",
    kitModel: {
      file: "coatRack.glb",
      minX: 0,
      minY: 0,
      minZ: -13.44,
      maxX: 44.8,
      maxY: 28,
      maxZ: 0,
    },
  },
  {
    key: "console-table-narrow",
    category: "entryway",
    nameEn: "Hallway console table",
    nameDe: "Flurkonsole",
    w: 100,
    l: 25,
    h: 78,
    color: "#8b5e3c",
    material: "wood",
    proceduralModel: { family: "legFrame" },
  },
  {
    key: "wall-mirror",
    category: "entryway",
    nameEn: "Wall mirror",
    nameDe: "Wandspiegel",
    w: 60,
    l: 4,
    h: 80,
    color: "#e59964",
    layer: "wall",
    elevation: 140,
    material: "glass",
    kitModel: {
      file: "bathroomMirror.glb",
      minX: 0,
      minY: 0,
      minZ: -4.88,
      maxX: 30.13,
      maxY: 43.46,
      maxZ: 9.56,
    },
  },
  {
    key: "wall-sconce",
    category: "entryway",
    nameEn: "Wall sconce",
    nameDe: "Wandleuchte",
    // Bumped up from 15x10 to be closer to lampWall.glb's own native
    // footprint now that it renders as the real model instead of a
    // procedural cone shade.
    w: 35,
    l: 20,
    h: 18,
    color: "#bdd2d6",
    layer: "wall",
    elevation: 160,
    material: "metal",
    isLightSource: true,
    // Corrected 2026-07: recorded bounding box was ~1.72x too large on
    // every axis vs. the actual lampWall.glb mesh (native footprint is
    // really ~22.7x15cm, not ~39x26cm as the old numbers implied).
    kitModel: {
      file: "lampWall.glb",
      minX: -11.33,
      minY: 0,
      minZ: 0,
      maxX: 11.33,
      maxY: 9.28,
      maxZ: 15.03,
    },
  },
  {
    key: "pendant-hallway",
    category: "entryway",
    nameEn: "Hallway pendant light",
    nameDe: "Flur-Pendelleuchte",
    w: 22,
    l: 22,
    h: 28,
    color: "#ffe996",
    shape: "circle",
    layer: "wall",
    elevation: 195,
    material: "metal",
    isLightSource: true,
    kitModel: {
      file: "lampSquareCeiling.glb",
      minX: 0,
      minY: 0,
      minZ: -12,
      maxX: 12,
      maxY: 23,
      maxZ: 0,
    },
  },
  {
    key: "ceiling-flush-mount",
    category: "entryway",
    nameEn: "Ceiling light",
    nameDe: "Deckenleuchte",
    w: 30,
    l: 30,
    h: 10,
    color: "#f8fafc",
    shape: "circle",
    layer: "wall",
    elevation: 230,
    material: "glass",
    isLightSource: true,
    proceduralModel: { family: "poleLamp", params: { mount: "ceiling", shade: "disc" } },
  },
  // Kids room
  {
    key: "bunk-bed",
    category: "kids",
    nameEn: "Bunk bed",
    nameDe: "Etagenbett",
    w: 140,
    l: 195,
    h: 170,
    color: "#f8ffff",
    material: "wood",
    // Corrected 2026-07: recorded minX/minY/minZ didn't match the actual
    // bedBunk.glb mesh, which is flush at X=0/Y=0 (not offset negative)
    // and only 109.5cm deep (not 189.2cm).
    kitModel: {
      file: "bedBunk.glb",
      minX: 0,
      minY: 0,
      minZ: -109.5,
      maxX: 57.1,
      maxY: 85,
      maxZ: 0,
    },
  },
  {
    key: "toy-chest",
    category: "kids",
    nameEn: "Toy chest",
    nameDe: "Spielzeugkiste",
    w: 80,
    l: 45,
    h: 45,
    color: "#f59e0b",
    material: "wood",
    proceduralModel: { family: "cabinetBox", params: { doorLines: 1 } },
  },
  {
    key: "kids-desk",
    category: "kids",
    nameEn: "Kids desk",
    nameDe: "Kinderschreibtisch",
    w: 90,
    l: 50,
    h: 55,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "desk.glb",
      minX: -1,
      minY: 0,
      minZ: -38,
      maxX: 72.45,
      maxY: 38.44,
      maxZ: 1.23,
    },
  },
  {
    key: "kids-chair",
    category: "kids",
    nameEn: "Kids chair",
    nameDe: "Kinderstuhl",
    w: 35,
    l: 35,
    h: 50,
    color: "#e59964",
    material: "plastic",
    kitModel: {
      file: "chairRounded.glb",
      minX: 0,
      minY: 0,
      minZ: -20,
      maxX: 20,
      maxY: 45.5,
      maxZ: 0,
    },
  },
  {
    key: "changing-table",
    category: "kids",
    nameEn: "Changing table",
    nameDe: "Wickeltisch",
    w: 90,
    l: 55,
    h: 95,
    color: "#fbcfe8",
    material: "wood",
    proceduralModel: { family: "legFrame", params: { shelfFrac: 0.25 } },
  },
  {
    key: "rocking-chair",
    category: "kids",
    nameEn: "Rocking chair",
    nameDe: "Schaukelstuhl",
    w: 60,
    l: 80,
    h: 90,
    color: "#f15e57",
    material: "wood",
    kitModel: { file: "loungeChair.glb", minX: 0, minY: 0, minZ: -41, maxX: 49, maxY: 46, maxZ: 0 },
  },
  {
    // "which only has borders" -- a real baby gate/low fence is just a rail
    // frame you can see through, never a solid panel, so this gets its own
    // procedural family (railGate) instead of any box/cabinet shape.
    key: "baby-gate",
    category: "kids",
    nameEn: "Baby gate",
    nameDe: "Babygitter",
    w: 80,
    l: 6,
    h: 75,
    color: "#e7e5e4",
    material: "plastic",
    proceduralModel: { family: "railGate", params: { spindleCount: 7 } },
  },
  {
    key: "ball-pit",
    category: "kids",
    nameEn: "Ball pit",
    nameDe: "Bällebad",
    w: 100,
    l: 100,
    h: 40,
    color: "#22d3ee",
    shape: "circle",
    material: "plastic",
    proceduralModel: { family: "ballPit" },
  },
  // Outdoor / balcony
  {
    key: "outdoor-table",
    category: "outdoor",
    nameEn: "Outdoor table",
    nameDe: "Gartentisch",
    w: 90,
    l: 90,
    h: 72,
    color: "#e59964",
    shape: "circle",
    material: "metal",
    kitModel: {
      file: "tableRound.glb",
      minX: 0,
      minY: -27,
      minZ: -80,
      maxX: 69.28,
      maxY: 9.67,
      maxZ: 0,
    },
  },
  {
    key: "outdoor-chair",
    category: "outdoor",
    nameEn: "Outdoor chair",
    nameDe: "Gartenstuhl",
    w: 50,
    l: 50,
    h: 85,
    color: "#e59964",
    material: "plastic",
    kitModel: { file: "chair.glb", minX: 0, minY: 0, minZ: -20, maxX: 20, maxY: 47, maxZ: 0 },
  },
  {
    key: "sun-lounger",
    category: "outdoor",
    nameEn: "Sun lounger",
    nameDe: "Sonnenliege",
    w: 60,
    l: 190,
    h: 35,
    color: "#d4d4d8",
    material: "fabric",
    proceduralModel: { family: "loungerShape" },
  },
  {
    key: "planter-box",
    category: "outdoor",
    nameEn: "Planter box",
    nameDe: "Pflanzkasten",
    w: 80,
    l: 30,
    h: 40,
    color: "#4d7c0f",
    material: "wood",
    proceduralModel: { family: "potAndFoliage" },
  },
  {
    key: "bbq-grill",
    category: "outdoor",
    nameEn: "BBQ grill",
    nameDe: "Grill",
    w: 60,
    l: 50,
    h: 100,
    color: "#27272a",
    material: "metal",
    proceduralModel: { family: "domedCart" },
  },
  {
    // Renamed from "Patio umbrella" -- the modeled dimensions are just the
    // weighted base, not an open umbrella canopy (which would be 250-300cm
    // across), so the old name overstated what's actually placed. Same key
    // kept for backward compatibility with already-saved layouts.
    key: "umbrella-stand",
    category: "outdoor",
    nameEn: "Umbrella stand",
    nameDe: "Sonnenschirmständer",
    w: 30,
    l: 30,
    h: 25,
    color: "#78716c",
    shape: "circle",
    material: "stone",
    proceduralModel: { family: "standAndPole" },
  },

  // ---------------------------------------------------------------------
  // UNDER layer -- sit beneath everything else, never collide with
  // anything (see collidesWithOthers in planner-math.ts). Very low `h` so
  // the 3D view renders them flush with the floor instead of as a box.
  // ---------------------------------------------------------------------
  {
    key: "rug",
    category: "decor",
    nameEn: "Rug",
    nameDe: "Teppich",
    w: 200,
    l: 140,
    h: 0.5,
    color: "#f15e57",
    layer: "under",
    material: "rug",
    kitModel: {
      file: "rugRectangle.glb",
      minX: 0,
      minY: 0,
      minZ: -92,
      maxX: 157,
      maxY: 1,
      maxZ: 0,
    },
  },
  {
    key: "rug-round",
    category: "decor",
    nameEn: "Round rug",
    nameDe: "Runder Teppich",
    w: 160,
    l: 160,
    h: 0.5,
    color: "#f15e57",
    layer: "under",
    shape: "circle",
    material: "rug",
    kitModel: { file: "rugRound.glb", minX: 0, minY: 0, minZ: -92, maxX: 92, maxY: 1, maxZ: 0 },
  },
  {
    key: "rug-small",
    category: "decor",
    nameEn: "Small rug",
    nameDe: "Kleiner Teppich",
    w: 90,
    l: 60,
    h: 0.5,
    color: "#e59964",
    layer: "under",
    material: "rug",
    kitModel: {
      file: "rugDoormat.glb",
      minX: 0,
      minY: 0,
      minZ: -23.7,
      maxX: 42.93,
      maxY: 1,
      maxZ: 0,
    },
  },
  {
    key: "doormat",
    category: "entryway",
    nameEn: "Doormat",
    nameDe: "Fussmatte",
    w: 60,
    l: 40,
    h: 1,
    color: "#e59964",
    layer: "under",
    material: "rug",
    kitModel: {
      file: "rugDoormat.glb",
      minX: 0,
      minY: 0,
      minZ: -23.7,
      maxX: 42.93,
      maxY: 1,
      maxZ: 0,
    },
  },
  {
    key: "runner-rug",
    category: "entryway",
    nameEn: "Hallway runner rug",
    nameDe: "Läufer",
    w: 70,
    l: 250,
    h: 0.5,
    color: "#9c6b4f",
    layer: "under",
    material: "rug",
  },
  {
    key: "floor-mat-kitchen",
    category: "kitchen",
    nameEn: "Kitchen floor mat",
    nameDe: "Küchenläufer",
    w: 80,
    l: 50,
    h: 0.8,
    color: "#94a3b8",
    layer: "under",
    material: "rug",
  },
  {
    key: "bath-mat",
    category: "bathroom",
    nameEn: "Bath mat",
    nameDe: "Badematte",
    w: 60,
    l: 45,
    h: 1,
    color: "#e59964",
    layer: "under",
    material: "rug",
    kitModel: {
      file: "rugDoormat.glb",
      minX: 0,
      minY: 0,
      minZ: -23.7,
      maxX: 42.93,
      maxY: 1,
      maxZ: 0,
    },
  },
  {
    key: "play-mat",
    category: "kids",
    nameEn: "Play mat",
    nameDe: "Spielmatte",
    w: 150,
    l: 150,
    h: 1.5,
    color: "#f15e57",
    layer: "under",
    material: "plastic",
    kitModel: { file: "rugSquare.glb", minX: 0, minY: 0, minZ: -92, maxX: 90.43, maxY: 1, maxZ: 0 },
  },

  // ---------------------------------------------------------------------
  // ON-TOP layer -- meant to be placed visually on a main-layer surface
  // (a desk, table, counter, media console); never collide with anything
  // (see collidesWithOthers in planner-math.ts). `h` is the object's own
  // height -- usually small (lamps, laptops, vases), though a propped-up
  // TV runs taller; the 3D view additionally elevates these above the
  // floor by default (see ON_TOP_DEFAULT_ELEVATION in use-room-planner.ts)
  // so they read as sitting on a surface rather than floating at floor
  // level. Dragging one onto a main item auto-elevates it to that item's
  // top surface (see findOnTopHost in planner-math.ts).
  // ---------------------------------------------------------------------
  {
    key: "desk-lamp",
    category: "office",
    nameEn: "Desk lamp",
    nameDe: "Schreibtischlampe",
    w: 20,
    l: 20,
    h: 40,
    color: "#ffe996",
    layer: "on-top",
    material: "metal",
    isLightSource: true,
    kitModel: {
      file: "lampSquareTable.glb",
      minX: 0,
      minY: 0,
      minZ: -12,
      maxX: 12,
      maxY: 29,
      maxZ: 0,
    },
  },
  {
    key: "table-lamp",
    category: "living",
    nameEn: "Table lamp",
    nameDe: "Tischlampe",
    w: 25,
    l: 25,
    h: 45,
    color: "#bdd2d6",
    layer: "on-top",
    shape: "circle",
    material: "fabric",
    isLightSource: true,
    kitModel: {
      file: "lampRoundTable.glb",
      minX: -1.6,
      minY: 0,
      minZ: -14.78,
      maxX: 13.6,
      maxY: 31.42,
      maxZ: 2.78,
    },
  },
  {
    key: "laptop",
    category: "office",
    nameEn: "Laptop",
    nameDe: "Laptop",
    // laptop.glb is modeled open (screen up), so h grew from the old
    // closed-lid procedural shape's 3cm to a real open-screen height.
    w: 35,
    l: 24,
    h: 22,
    color: "#4e6363",
    layer: "on-top",
    material: "metal",
    kitModel: {
      // Corrected 2026-07: the previous values (60 x 36.77 x 54.56) were
      // ~2.27x too large on every axis vs. the actual laptop.glb mesh --
      // likely a leftover measurement from a different scale factor. That
      // inflated "native size" made computeModelScale divide the target
      // dims by a too-big number, so the rendered model came out visibly
      // smaller than its own item footprint in 3D (fine in 2D, since 2D
      // only ever draws the footprint rectangle, never the mesh itself).
      file: "laptop.glb",
      minX: 0,
      minY: 0,
      minZ: -24.01,
      maxX: 26.4,
      maxY: 16.18,
      maxZ: 0,
    },
  },
  {
    key: "monitor",
    category: "office",
    nameEn: "Monitor",
    nameDe: "Monitor",
    w: 55,
    l: 20,
    h: 40,
    color: "#4e6363",
    layer: "on-top",
    material: "metal",
    kitModel: {
      file: "computerScreen.glb",
      minX: 0,
      minY: 0,
      minZ: -10.4,
      maxX: 39.27,
      maxY: 29.43,
      maxZ: 0,
    },
  },
  {
    key: "printer",
    category: "office",
    nameEn: "Printer",
    nameDe: "Drucker",
    w: 40,
    l: 35,
    h: 20,
    color: "#71717a",
    layer: "on-top",
    material: "plastic",
    proceduralModel: { family: "panelAccentBox", params: { panelHFrac: 0.4, colorOffset: -0.15 } },
  },
  {
    key: "router-box",
    category: "office",
    nameEn: "Router",
    nameDe: "Router",
    w: 20,
    l: 12,
    h: 4,
    color: "#27272a",
    layer: "on-top",
    material: "plastic",
  },
  {
    key: "books-stack",
    category: "living",
    nameEn: "Stack of books",
    nameDe: "Bücherstapel",
    // l/h tightened 2026-07 to match books.glb's own native aspect ratio
    // (its bounding box, unlike some other kitModel entries, was already
    // measured correctly) -- the old 25x20x15 stretched the model roughly
    // 1.66x on X but 2.12x on Z and 1.44x on Y, which is uneven enough to
    // visibly warp a stack of straight-edged books. w stays 25 so the 2D
    // footprint doesn't shift; l/h now scale by ~1.66x uniformly instead.
    w: 25,
    l: 16,
    h: 17,
    color: "#9b4c49",
    layer: "on-top",
    material: "leather",
    kitModel: {
      file: "books.glb",
      minX: 0,
      minY: 0,
      minZ: -9.45,
      maxX: 15.04,
      maxY: 10.39,
      maxZ: 0,
    },
  },
  {
    key: "tray",
    category: "living",
    nameEn: "Tray",
    nameDe: "Tablett",
    w: 35,
    l: 25,
    h: 3,
    color: "#d6d3d1",
    layer: "on-top",
    material: "metal",
  },
  {
    key: "vase",
    category: "decor",
    nameEn: "Vase",
    nameDe: "Vase",
    w: 15,
    l: 15,
    h: 25,
    color: "#93c5fd",
    layer: "on-top",
    shape: "circle",
    material: "ceramic",
    proceduralModel: { family: "taperedVessel", params: { flame: false } },
  },
  {
    key: "plant-small",
    category: "decor",
    nameEn: "Small potted plant",
    nameDe: "Kleine Topfpflanze",
    w: 20,
    l: 20,
    h: 30,
    color: "#2ed193",
    layer: "on-top",
    shape: "circle",
    material: "plant",
    kitModel: {
      file: "plantSmall1.glb",
      minX: -4.73,
      minY: 0,
      minZ: -4.73,
      maxX: 4.73,
      maxY: 14,
      maxZ: 4.73,
    },
  },
  {
    key: "picture-frame",
    category: "decor",
    nameEn: "Picture frame",
    nameDe: "Bilderrahmen",
    w: 15,
    l: 10,
    h: 20,
    color: "#d6d3d1",
    layer: "on-top",
    material: "wood",
    proceduralModel: {
      family: "panelAccentBox",
      params: { panelWFrac: 0.7, panelHFrac: 0.7, colorOffset: 0.25 },
    },
  },
  {
    key: "candle",
    category: "decor",
    nameEn: "Candle",
    nameDe: "Kerze",
    w: 10,
    l: 10,
    h: 12,
    color: "#fef3c7",
    layer: "on-top",
    shape: "circle",
    material: "plastic",
    proceduralModel: { family: "taperedVessel", params: { flame: true } },
  },
  {
    key: "fruit-bowl",
    category: "kitchen",
    nameEn: "Fruit bowl",
    nameDe: "Obstschale",
    w: 25,
    l: 25,
    h: 12,
    color: "#f97316",
    layer: "on-top",
    shape: "circle",
    material: "ceramic",
  },
  {
    key: "microwave",
    category: "kitchen",
    nameEn: "Microwave",
    nameDe: "Mikrowelle",
    w: 45,
    l: 35,
    h: 30,
    color: "#5e7777",
    layer: "on-top",
    material: "metal",
    kitModel: {
      file: "kitchenMicrowave.glb",
      minX: 0,
      minY: 0,
      minZ: -22,
      maxX: 29,
      maxY: 18,
      maxZ: 1,
    },
  },
  {
    key: "toaster",
    category: "kitchen",
    nameEn: "Toaster",
    nameDe: "Toaster",
    w: 25,
    l: 15,
    h: 20,
    color: "#5e7777",
    layer: "on-top",
    material: "metal",
    kitModel: { file: "toaster.glb", minX: -9.4, minY: 0, minZ: -5, maxX: 9.4, maxY: 13, maxZ: 5 },
  },
  {
    key: "coffee-maker",
    category: "kitchen",
    nameEn: "Coffee maker",
    nameDe: "Kaffeemaschine",
    w: 20,
    l: 20,
    h: 35,
    color: "#44403c",
    layer: "on-top",
    material: "metal",
    proceduralModel: {
      family: "panelAccentBox",
      params: { panelWFrac: 0.5, panelHFrac: 0.3, colorOffset: -0.2 },
    },
  },
  {
    key: "stand-mixer",
    category: "kitchen",
    nameEn: "Stand mixer",
    nameDe: "Küchenmaschine",
    w: 22,
    l: 22,
    h: 30,
    color: "#b2d3c4",
    layer: "on-top",
    material: "metal",
    kitModel: {
      file: "kitchenBlender.glb",
      minX: 0,
      minY: 0,
      minZ: -10.91,
      maxX: 13.58,
      maxY: 22.75,
      maxZ: 0,
    },
  },
  {
    key: "toiletries-tray",
    category: "bathroom",
    nameEn: "Toiletries tray",
    nameDe: "Utensilienschale",
    w: 25,
    l: 15,
    h: 5,
    color: "#f8fafc",
    layer: "on-top",
    material: "ceramic",
  },
  {
    key: "key-tray",
    category: "entryway",
    nameEn: "Key & mail tray",
    nameDe: "Schlüsselschale",
    w: 20,
    l: 12,
    h: 3,
    color: "#8b5e3c",
    layer: "on-top",
    material: "ceramic",
  },
  {
    key: "tv-55",
    category: "living",
    nameEn: '55" TV',
    nameDe: '55" Fernseher',
    w: 122,
    l: 15,
    h: 68,
    color: "#4e6363",
    layer: "on-top",
    material: "metal",
    kitModel: {
      file: "televisionModern.glb",
      minX: -34.24,
      minY: 0,
      minZ: -6.42,
      maxX: 34.24,
      maxY: 45.48,
      maxZ: 6.42,
    },
  },
  {
    key: "tv-65",
    category: "living",
    nameEn: '65" TV',
    nameDe: '65" Fernseher',
    w: 144,
    l: 16,
    h: 81,
    color: "#4e6363",
    layer: "on-top",
    material: "metal",
    kitModel: {
      file: "televisionModern.glb",
      minX: -34.24,
      minY: 0,
      minZ: -6.42,
      maxX: 34.24,
      maxY: 45.48,
      maxZ: 6.42,
    },
  },
  {
    key: "tv-75",
    category: "living",
    nameEn: '75" TV',
    nameDe: '75" Fernseher',
    w: 166,
    l: 18,
    h: 93,
    color: "#4e6363",
    layer: "on-top",
    material: "metal",
    kitModel: {
      file: "televisionModern.glb",
      minX: -34.24,
      minY: 0,
      minZ: -6.42,
      maxX: 34.24,
      maxY: 45.48,
      maxZ: 6.42,
    },
  },
  {
    key: "ps5",
    category: "living",
    nameEn: "PS5 console",
    nameDe: "PS5-Konsole",
    w: 16,
    l: 32,
    h: 38,
    color: "#e8e8ea",
    layer: "on-top",
    material: "plastic",
  },
  {
    key: "switch-2",
    category: "living",
    nameEn: "Nintendo Switch 2",
    nameDe: "Nintendo Switch 2",
    w: 16,
    l: 6,
    h: 12,
    color: "#27272a",
    layer: "on-top",
    material: "plastic",
  },

  // ---------------------------------------------------------------------
  // WALL layer -- mounted on the wall at a fixed height regardless of
  // what's on the floor beneath (sconces, art, mirrors, ceiling/pendant
  // lighting, cabinets/shelving hung above counter height, ...). Never
  // collide with anything, and excluded from the "on-top" auto-settle-
  // onto-furniture behavior (see ItemLayer in types/planner.ts and
  // WALL_MOUNT_DEFAULT_ELEVATION in use-room-planner.ts) so dragging one
  // never resets its height. A handful of the kitchen/entryway/bathroom
  // wall items above are grouped with their room category instead of here
  // for catalog discoverability; this section covers the rest.
  // ---------------------------------------------------------------------
  {
    key: "kitchen-wall-cabinet",
    category: "kitchen",
    nameEn: "Upper wall cabinet",
    nameDe: "Hängeschrank",
    w: 80,
    l: 35,
    h: 70,
    color: "#e59964",
    layer: "wall",
    elevation: 145,
    material: "wood",
    kitModel: {
      file: "kitchenCabinetUpperDouble.glb",
      minX: 0,
      minY: 0,
      minZ: -21,
      maxX: 43,
      maxY: 39,
      maxZ: 1,
    },
  },
  {
    key: "range-hood",
    category: "kitchen",
    nameEn: "Range hood",
    nameDe: "Dunstabzugshaube",
    w: 60,
    l: 35,
    h: 40,
    color: "#5e7777",
    layer: "wall",
    elevation: 160,
    material: "metal",
    kitModel: {
      file: "hoodModern.glb",
      minX: 0,
      minY: -3,
      minZ: -28.49,
      maxX: 43,
      maxY: 36.95,
      maxZ: 0,
    },
  },
  {
    key: "open-shelving-kitchen",
    category: "kitchen",
    nameEn: "Open kitchen shelf",
    nameDe: "Küchen-Wandregal",
    w: 80,
    l: 25,
    h: 15,
    color: "#a07855",
    layer: "wall",
    elevation: 140,
    material: "wood",
  },
  {
    key: "vanity-mirror",
    category: "bathroom",
    nameEn: "Vanity mirror",
    nameDe: "Badspiegel",
    w: 70,
    l: 4,
    h: 60,
    color: "#e59964",
    layer: "wall",
    elevation: 140,
    material: "glass",
    kitModel: {
      file: "bathroomMirror.glb",
      minX: 0,
      minY: 0,
      minZ: -4.88,
      maxX: 30.13,
      maxY: 43.46,
      maxZ: 9.56,
    },
  },
  {
    key: "medicine-cabinet",
    category: "bathroom",
    nameEn: "Medicine cabinet",
    nameDe: "Spiegelschrank",
    w: 50,
    l: 15,
    h: 65,
    color: "#e59964",
    layer: "wall",
    elevation: 130,
    material: "glass",
    kitModel: {
      file: "bathroomCabinet.glb",
      minX: 20,
      minY: 0,
      minZ: -21,
      maxX: 43,
      maxY: 39,
      maxZ: -8,
    },
  },
  // ---------------------------------------------------------------------
  // Kenney asset expansion -- unused pieces from the same Furniture Kit
  // (see resources/kenney_furniture-kit/) added after a manual review of
  // which ones filled a real gap or upgraded an existing procedural/box
  // preset to a real mesh. Appended here rather than interleaved into each
  // category's original spot above to keep this batch easy to review as
  // one unit; PRESET_ICON entries for every key below live in the map that
  // follows this array.
  // ---------------------------------------------------------------------

  // Bathroom
  {
    key: "bathroom-cabinet-drawer",
    category: "bathroom",
    nameEn: "Cabinet with drawer",
    nameDe: "Schrank mit Schublade",
    w: 45,
    l: 40,
    h: 85,
    color: "#e59964",
    material: "wood",
    // Corrected 2026-07: minY/maxZ were off vs. the actual
    // bathroomCabinetDrawer.glb mesh (real minY is 5.82, not 0; real maxZ
    // is -13, not 2).
    kitModel: {
      file: "bathroomCabinetDrawer.glb",
      minX: 0,
      minY: 5.82,
      minZ: -45,
      maxX: 43,
      maxY: 53,
      maxZ: -13,
    },
  },
  {
    key: "shower-round",
    category: "bathroom",
    nameEn: "Round shower",
    nameDe: "Runde Dusche",
    w: 90,
    l: 90,
    h: 200,
    color: "#ffffff",
    shape: "circle",
    material: "glass",
    // Corrected 2026-07: recorded minX/maxZ didn't match the actual
    // showerRound.glb mesh, which sits corner-flush at X=0/Z=0 (not
    // centered on X the way the old -37.84..56.18 range implied).
    kitModel: {
      file: "showerRound.glb",
      minX: 0,
      minY: 0,
      minZ: -56.18,
      maxX: 56.18,
      maxY: 109.4,
      maxZ: 0,
    },
  },

  // Kitchen
  {
    key: "kitchen-base-cabinet",
    category: "kitchen",
    nameEn: "Base cabinet",
    nameDe: "Unterschrank",
    w: 50,
    l: 55,
    h: 85,
    color: "#bdd2d6",
    material: "wood",
    // maxZ corrected 2026-07: recorded 3, actual mesh is flush at 0.
    kitModel: {
      file: "kitchenCabinet.glb",
      minX: 0,
      minY: 0,
      minZ: -45,
      maxX: 43,
      maxY: 45,
      maxZ: 0,
    },
  },
  {
    key: "kitchen-base-cabinet-drawer",
    category: "kitchen",
    nameEn: "Base cabinet w/ drawer",
    nameDe: "Unterschrank mit Schublade",
    w: 45,
    l: 55,
    h: 85,
    color: "#bdd2d6",
    material: "wood",
    // maxZ corrected 2026-07: recorded 3, actual mesh is flush at 0.
    kitModel: {
      file: "kitchenCabinetDrawer.glb",
      minX: 0,
      minY: 0,
      minZ: -45,
      maxX: 43,
      maxY: 45,
      maxZ: 0,
    },
  },
  {
    key: "kitchen-bar",
    category: "kitchen",
    nameEn: "Breakfast bar",
    nameDe: "Bartheke",
    w: 45,
    l: 42,
    h: 100,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "kitchenBar.glb",
      minX: 0,
      minY: 0,
      minZ: -21,
      maxX: 43,
      maxY: 42,
      maxZ: 0,
    },
  },
  {
    key: "kitchen-coffee-machine",
    category: "kitchen",
    nameEn: "Coffee machine",
    nameDe: "Kaffeemaschine",
    w: 25,
    l: 30,
    h: 32,
    color: "#5e7777",
    layer: "on-top",
    material: "plastic",
    // Corrected 2026-07: recorded bounding box didn't match the actual
    // kitchenCoffeeMachine.glb mesh on any axis.
    kitModel: {
      file: "kitchenCoffeeMachine.glb",
      minX: 0,
      minY: 0,
      minZ: -24.02,
      maxX: 18.95,
      maxY: 17.75,
      maxZ: 0,
    },
  },

  // Living / seating
  {
    key: "sofa-corner",
    category: "seating",
    nameEn: "Corner sofa",
    nameDe: "Ecksofa",
    w: 200,
    l: 200,
    h: 85,
    color: "#f15e57",
    material: "fabric",
    kitModel: {
      file: "loungeSofaCorner.glb",
      minX: 0,
      minY: 0,
      minZ: -98,
      maxX: 98,
      maxY: 46,
      maxZ: 0,
    },
  },
  {
    key: "coffee-table-glass",
    category: "tables",
    nameEn: "Glass coffee table",
    nameDe: "Glas-Couchtisch",
    w: 100,
    l: 55,
    h: 40,
    color: "#bdd2d6",
    material: "glass",
    kitModel: {
      file: "tableCoffeeGlass.glb",
      minX: -46.1,
      minY: 0,
      minZ: -30,
      maxX: 20,
      maxY: 23,
      maxZ: 10,
    },
  },
  {
    key: "dining-table-glass",
    category: "dining",
    nameEn: "Glass dining table",
    nameDe: "Glas-Esstisch",
    w: 150,
    l: 85,
    h: 75,
    color: "#bdd2d6",
    material: "glass",
    kitModel: {
      file: "tableGlass.glb",
      minX: 0,
      minY: 0,
      minZ: -44.74,
      maxX: 84.15,
      maxY: 32.67,
      maxZ: 0,
    },
  },
  {
    key: "speaker",
    category: "living",
    nameEn: "Speaker",
    nameDe: "Lautsprecher",
    w: 18,
    l: 18,
    h: 65,
    color: "#e59964",
    material: "plastic",
    kitModel: {
      file: "speaker.glb",
      minX: 0,
      minY: 0,
      minZ: -14.8,
      maxX: 14.8,
      maxY: 63.64,
      maxZ: 0,
    },
  },
  {
    key: "pillow",
    category: "living",
    nameEn: "Throw pillow",
    nameDe: "Zierkissen",
    w: 45,
    l: 45,
    h: 15,
    color: "#f15e57",
    layer: "on-top",
    material: "fabric",
    kitModel: {
      file: "pillow.glb",
      minX: 0,
      minY: 0,
      minZ: -8.85,
      maxX: 23,
      maxY: 22.22,
      maxZ: 0,
    },
  },
  {
    key: "pillow-long",
    category: "living",
    nameEn: "Lumbar pillow",
    nameDe: "Nackenrolle",
    w: 55,
    l: 20,
    h: 15,
    color: "#f15e57",
    layer: "on-top",
    material: "fabric",
    kitModel: {
      file: "pillowLong.glb",
      minX: 0,
      minY: 0,
      minZ: -8.85,
      maxX: 38.66,
      maxY: 22.22,
      maxZ: 0,
    },
  },
  {
    key: "television-vintage",
    category: "living",
    nameEn: "Vintage TV",
    nameDe: "Retro-Fernseher",
    w: 45,
    l: 45,
    h: 45,
    color: "#e59964",
    layer: "on-top",
    material: "plastic",
    kitModel: {
      file: "televisionVintage.glb",
      minX: 0,
      minY: 0,
      minZ: -27,
      maxX: 41,
      maxY: 27,
      maxZ: 0,
    },
  },
  {
    key: "radio",
    category: "living",
    nameEn: "Radio",
    nameDe: "Radio",
    w: 32,
    l: 12,
    h: 20,
    color: "#5e7777",
    layer: "on-top",
    material: "plastic",
    kitModel: {
      file: "radio.glb",
      minX: 0,
      minY: 0,
      minZ: -9.75,
      maxX: 31.5,
      maxY: 22.82,
      maxZ: 0,
    },
  },
  {
    key: "cardboard-box-closed",
    category: "decor",
    nameEn: "Moving box",
    nameDe: "Umzugskarton",
    w: 40,
    l: 40,
    h: 35,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "cardboardBoxClosed.glb",
      minX: 0,
      minY: 0,
      minZ: -21.25,
      maxX: 21.25,
      maxY: 28.1,
      maxZ: 0,
    },
  },
  {
    key: "cardboard-box-open",
    category: "decor",
    nameEn: "Open moving box",
    nameDe: "Offener Umzugskarton",
    w: 40,
    l: 40,
    h: 32,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "cardboardBoxOpen.glb",
      minX: -7.97,
      minY: 0,
      minZ: -21.25,
      maxX: 29.22,
      maxY: 28.1,
      maxZ: 0,
    },
  },
  {
    key: "plant-small-2",
    category: "decor",
    nameEn: "Potted fern",
    nameDe: "Farn im Topf",
    w: 20,
    l: 20,
    h: 30,
    color: "#2ed193",
    shape: "circle",
    material: "plant",
    // Corrected 2026-07: recorded bounding box was exactly 2x too large on
    // every axis vs. the actual plantSmall2.glb mesh.
    kitModel: {
      file: "plantSmall2.glb",
      minX: -4.73,
      minY: 0,
      minZ: -4.73,
      maxX: 4.73,
      maxY: 14,
      maxZ: 4.73,
    },
  },
  {
    key: "plant-small-3",
    category: "decor",
    nameEn: "Snake plant",
    nameDe: "Bogenhanf",
    w: 18,
    l: 20,
    h: 32,
    color: "#2ed193",
    shape: "circle",
    material: "plant",
    // Corrected 2026-07: recorded bounding box didn't match the actual
    // plantSmall3.glb mesh (~1.7-2.3x too large per axis).
    kitModel: {
      file: "plantSmall3.glb",
      minX: -4.9,
      minY: 0,
      minZ: -4.24,
      maxX: 4.9,
      maxY: 14.5,
      maxZ: 4.24,
    },
  },

  // Office
  {
    key: "computer-keyboard",
    category: "office",
    nameEn: "Keyboard",
    nameDe: "Tastatur",
    w: 30,
    l: 12,
    h: 3,
    color: "#4e6363",
    layer: "on-top",
    material: "plastic",
    kitModel: {
      file: "computerKeyboard.glb",
      minX: 0,
      minY: 0,
      minZ: -11.82,
      maxX: 28.22,
      maxY: 2.76,
      maxZ: 0,
    },
  },
  {
    key: "computer-mouse",
    category: "office",
    nameEn: "Mouse",
    nameDe: "Maus",
    w: 6,
    l: 10,
    h: 3,
    color: "#4e6363",
    layer: "on-top",
    material: "plastic",
    kitModel: {
      file: "computerMouse.glb",
      minX: -2.48,
      minY: 0,
      minZ: -8.51,
      maxX: 2.48,
      maxY: 2.36,
      maxZ: 0,
    },
  },
  {
    // No matching Kenney Furniture Kit model for a PC case -- reuses the
    // panelAccentBox procedural family (a box with a single recessed front
    // panel) with a tall, dark accent strip standing in for the front
    // mesh/RGB strip of a mid-tower gaming PC.
    key: "pc-tower",
    category: "office",
    nameEn: "Tower PC",
    nameDe: "PC-Gehäuse",
    w: 20,
    l: 45,
    h: 45,
    color: "#1f2937",
    material: "metal",
    proceduralModel: {
      family: "panelAccentBox",
      params: { panelWFrac: 0.55, panelHFrac: 0.92, colorOffset: -0.35 },
    },
  },
  {
    // No matching Kenney model either -- custom gamepadShape (see
    // procedural-models.ts): a flat body with two raised thumbstick nubs.
    key: "gamepad",
    category: "office",
    nameEn: "Gamepad",
    nameDe: "Controller",
    w: 15,
    l: 10,
    h: 6,
    color: "#27272a",
    layer: "on-top",
    material: "plastic",
    proceduralModel: { family: "gamepadShape" },
  },

  // Kids
  {
    key: "plush-bear",
    category: "kids",
    nameEn: "Teddy bear",
    nameDe: "Teddybär",
    w: 25,
    l: 20,
    h: 45,
    color: "#a5754c",
    layer: "on-top",
    material: "fabric",
    kitModel: {
      file: "bear.glb",
      minX: 0,
      minY: 0,
      minZ: -24.75,
      maxX: 38.97,
      maxY: 45,
      maxZ: 0,
    },
  },

  // ---------------------------------------------------------------------
  // Structural -- stair models from the same Kenney Furniture Kit, left
  // out of the original catalog expansion because there was no multi-floor
  // feature yet to make them meaningful (see resources/kenney_furniture-
  // kit/). Now that floors exist (src/lib/floors.ts), they're worth having
  // even though there's no functional floor-to-floor linkage in this app
  // yet -- placing one is purely decorative/visual, same as any other
  // furniture piece, not an actual passage between floors.
  // ---------------------------------------------------------------------
  {
    key: "stairs-straight",
    category: "structural",
    nameEn: "Staircase",
    nameDe: "Treppe",
    w: 182,
    l: 79,
    h: 134,
    color: "#e59964",
    material: "wood",
    kitModel: {
      file: "stairs.glb",
      minX: 0,
      minY: 0,
      minZ: -79,
      maxX: 182.34,
      maxY: 133.95,
      maxZ: 0,
    },
  },
  {
    key: "stairs-corner",
    category: "structural",
    nameEn: "Corner staircase",
    nameDe: "Ecktreppe",
    w: 177,
    l: 143,
    h: 134,
    color: "#ad744c",
    material: "wood",
    kitModel: {
      file: "stairsCorner.glb",
      minX: 16.39,
      minY: 0,
      minZ: -142.58,
      maxX: 193.76,
      maxY: 133.95,
      maxZ: 0,
    },
  },
  {
    key: "stairs-open",
    category: "structural",
    nameEn: "Open staircase",
    nameDe: "Offene Treppe",
    w: 182,
    l: 79,
    h: 134,
    color: "#bdd2d6",
    material: "wood",
    kitModel: {
      file: "stairsOpen.glb",
      minX: 0,
      minY: 0,
      minZ: -79,
      maxX: 182.34,
      maxY: 133.95,
      maxZ: 0,
    },
  },
  {
    key: "stairs-open-single",
    category: "structural",
    nameEn: "Open staircase, single rail",
    nameDe: "Offene Treppe, einseitig",
    w: 182,
    l: 79,
    h: 134,
    color: "#bdd2d6",
    material: "wood",
    kitModel: {
      file: "stairsOpenSingle.glb",
      minX: 0,
      minY: 0,
      minZ: -79,
      maxX: 182.34,
      maxY: 133.95,
      maxZ: 0,
    },
  },
];

export const PRESET_BY_KEY = Object.fromEntries(PRESETS.map((p) => [p.key, p]));

// Lucide icon per preset key (catalog + item rendering)
export const PRESET_ICON: Record<string, LucideIcon> = {
  "chair-office": Armchair,
  armchair: Armchair,
  sofa: Sofa,
  loveseat: Sofa,
  "accent-chair": Armchair,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  nightstand: Table2,
  dresser: Boxes,
  "vanity-table": Table2,
  "vanity-stool": Circle,
  "mirror-full-length": RectangleVertical,
  "bedside-bench": StretchHorizontal,
  desk: LampDesk,
  "round-table": Circle,
  "coffee-table": RectangleHorizontal,
  "side-table": Square,
  bookshelf: BookOpen,
  wardrobe: Archive,
  "filing-cabinet": Files,
  "cube-shelf": LayoutGrid,
  "ladder-bookcase": BookOpen,
  "door-wardrobe": Archive,
  "leg-cabinet": Files,
  stove: CookingPot,
  sink: Droplets,
  fridge: Refrigerator,
  "kitchen-island": LayoutGrid,
  dishwasher: Waves,
  oven: Flame,
  "pantry-cabinet": PackageOpen,
  "kitchen-cart": Boxes,
  "trash-bin": Trash2,
  "trash-bin-small": Trash2,
  "trash-bin-large": Trash2,
  "recycling-box": Recycle,
  "wine-fridge": Wine,
  toilet: Toilet,
  bathtub: Bath,
  "shower-stall": ShowerHead,
  "bathroom-sink-vanity": Droplet,
  "bathroom-cabinet": PackageOpen,
  "towel-rack": StretchHorizontal,
  "washing-machine": WashingMachine,
  "laundry-basket": Recycle,
  "linen-closet": Archive,
  bidet: Toilet,
  "soaking-tub": Bath,
  plant: Sprout,
  "floor-lamp": Lamp,
  "planter-tall": TreePine,
  curtains: PanelsLeftRight,
  blinds: Blinds,
  "canvas-art-large": Image,
  "tv-stand": Tv,
  recliner: Armchair,
  ottoman: Circle,
  "console-table": Table2,
  fireplace: Flame,
  "bar-cart": Boxes,
  "pendant-light": LampCeiling,
  "dining-table-rect": Table,
  "dining-table-round": Circle,
  "dining-chair": Armchair,
  sideboard: Boxes,
  "bar-stool": Circle,
  "buffet-hutch": Boxes,
  "dining-bench": StretchHorizontal,
  "chandelier-dining": LampCeiling,
  "office-desk-l": Table2,
  whiteboard: PanelTop,
  "standing-desk": Table2,
  "desk-pedestal": Boxes,
  "office-credenza": Archive,
  "guest-chair": Armchair,
  "room-divider": Columns2,
  corkboard: Presentation,
  "shoe-rack": Rows3,
  "coat-rack": Shirt,
  "entryway-bench": StretchHorizontal,
  "coat-hooks-wall": Shirt,
  "console-table-narrow": Table2,
  "wall-mirror": Frame,
  "wall-sconce": LampWallUp,
  "pendant-hallway": LampCeiling,
  "ceiling-flush-mount": Lightbulb,
  "bunk-bed": Layers,
  "toy-chest": ToyBrick,
  "kids-desk": Table2,
  "kids-chair": Armchair,
  "changing-table": Table2,
  "rocking-chair": Armchair,
  "baby-gate": Fence,
  "ball-pit": Volleyball,
  "outdoor-table": Circle,
  "outdoor-chair": Armchair,
  "sun-lounger": Sun,
  "planter-box": Flower2,
  "bbq-grill": Flame,
  "umbrella-stand": Umbrella,
  rug: Square,
  "rug-round": Circle,
  "rug-small": Square,
  doormat: Square,
  "runner-rug": Rows2,
  "floor-mat-kitchen": Square,
  "bath-mat": Square,
  "play-mat": Grid2x2,
  "desk-lamp": LampDesk,
  "table-lamp": Lamp,
  laptop: Laptop,
  monitor: Monitor,
  printer: Printer,
  "router-box": Router,
  "books-stack": BookOpen,
  tray: SquareStack,
  vase: Amphora,
  "plant-small": Sprout,
  "picture-frame": Frame,
  candle: Flame,
  "fruit-bowl": Apple,
  microwave: Microwave,
  toaster: Zap,
  "coffee-maker": Coffee,
  "stand-mixer": Blend,
  "toiletries-tray": SprayCan,
  "key-tray": SquareStack,
  "tv-55": Tv,
  "tv-65": Tv,
  "tv-75": Tv,
  ps5: Gamepad2,
  "switch-2": Joystick,
  "kitchen-wall-cabinet": PackageOpen,
  "range-hood": Wind,
  "open-shelving-kitchen": Rows3,
  "vanity-mirror": RectangleVertical,
  "medicine-cabinet": PackageOpen,
  // Kenney asset expansion (see the matching comment in PRESETS above)
  "bathroom-cabinet-drawer": Boxes,
  "shower-round": ShowerHead,
  "kitchen-base-cabinet": Rows2,
  "kitchen-base-cabinet-drawer": Boxes,
  "kitchen-bar": Wine,
  "kitchen-coffee-machine": Coffee,
  "sofa-corner": Sofa,
  "coffee-table-glass": RectangleHorizontal,
  "dining-table-glass": Table,
  speaker: Speaker,
  pillow: Square,
  "pillow-long": StretchHorizontal,
  "television-vintage": Tv,
  radio: Radio,
  "cardboard-box-closed": Package,
  "cardboard-box-open": PackageOpen,
  "plant-small-2": Flower2,
  "plant-small-3": Sprout,
  "computer-keyboard": Keyboard,
  "computer-mouse": Mouse,
  "plush-bear": PawPrint,
  "pc-tower": Cpu,
  gamepad: Gamepad,
  "stairs-straight": TrendingUp,
  "stairs-corner": TrendingUp,
  "stairs-open": TrendingUp,
  "stairs-open-single": TrendingUp,
};

export function iconUrlForItem(it: Item): string | undefined {
  if (it.icon && PRESET_BY_KEY[it.icon]) return PRESET_BY_KEY[it.icon].iconUrl;
  // legacy back-compat
  if (it.kind === "chair") return chairBaseUrl;
  return undefined;
}

/**
 * Real-world height (cm) to use for the 3D view when an item doesn't carry
 * its own explicit `height`. The catalog (`PRESETS` above) is the source of
 * truth -- covers every current preset. The switch below only exists as a
 * fallback for items that predate the `h` field (old saved rooms) or that
 * don't match a catalog key at all (custom boxes), so it intentionally
 * keeps the same defaults this function always used for those legacy keys.
 */
export function getDefaultHeight(icon?: string, kind?: string): number {
  if (icon) {
    const presetH = PRESET_BY_KEY[icon]?.h;
    if (presetH !== undefined) return presetH;
  }
  if (kind === "chair") return 80;
  if (!icon) return 75; // default custom box height
  switch (icon) {
    case "chair-office":
      return 85;
    case "armchair":
      return 80;
    case "sofa":
      return 80;
    case "bed-double":
    case "bed-single":
      return 45;
    case "desk":
    case "round-table":
      return 75;
    case "coffee-table":
      return 45;
    case "side-table":
      return 55;
    case "bookshelf":
      return 180;
    case "wardrobe":
      return 200;
    case "filing-cabinet":
      return 120;
    case "stove":
    case "sink":
      return 90;
    case "fridge":
      return 180;
    case "toilet":
      return 75;
    case "bathtub":
      return 60;
    case "plant":
      return 80;
    case "floor-lamp":
      return 160;
    case "rug":
      return 0.5; // flat on floor
    default:
      return 75;
  }
}

/**
 * The actual 3D render height for an item, accounting for Item.placedOnId
 * (see that field's own doc comment in types/planner.ts). An item riding on
 * top of another ignores its own stored `elevation` entirely and instead
 * sits at its host's current top surface (host elevation + host height) --
 * computed fresh from `allItems` on every call rather than cached/stored,
 * so resizing or moving the host keeps every item riding on it visually
 * correct with no separate sync step. Falls back to the item's own
 * elevation (or 0) if the referenced host no longer exists (e.g. a
 * mid-flight state during an undo/redo snapshot swap) or placedOnId isn't set.
 */
export function resolveEffectiveElevation(item: Item, allItems: Item[]): number {
  if (item.placedOnId) {
    const host = allItems.find((h) => h.id === item.placedOnId);
    if (host) {
      const hostHeight = host.height ?? getDefaultHeight(host.icon, host.kind);
      return (host.elevation ?? 0) + hostHeight;
    }
  }
  return item.elevation ?? 0;
}
