/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as HomeHomeIdIndexRouteImport } from './routes/home.$homeId.index'
import { Route as HomeHomeIdRoomRoomIdRouteImport } from './routes/home.$homeId.room.$roomId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHomeIdIndexRoute = HomeHomeIdIndexRouteImport.update({
  id: '/home/$homeId/',
  path: '/home/$homeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHomeIdRoomRoomIdRoute = HomeHomeIdRoomRoomIdRouteImport.update({
  id: '/home/$homeId/room/$roomId',
  path: '/home/$homeId/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/': typeof RoomsIndexRoute
  '/home/$homeId/': typeof HomeHomeIdIndexRoute
  '/home/$homeId/room/$roomId': typeof HomeHomeIdRoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms': typeof RoomsIndexRoute
  '/home/$homeId': typeof HomeHomeIdIndexRoute
  '/home/$homeId/room/$roomId': typeof HomeHomeIdRoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/': typeof RoomsIndexRoute
  '/home/$homeId/': typeof HomeHomeIdIndexRoute
  '/home/$homeId/room/$roomId': typeof HomeHomeIdRoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/room/$roomId'
    | '/rooms/$roomId'
    | '/rooms/'
    | '/home/$homeId/'
    | '/home/$homeId/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/room/$roomId'
    | '/rooms/$roomId'
    | '/rooms'
    | '/home/$homeId'
    | '/home/$homeId/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/room/$roomId'
    | '/rooms/$roomId'
    | '/rooms/'
    | '/home/$homeId/'
    | '/home/$homeId/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  HomeHomeIdIndexRoute: typeof HomeHomeIdIndexRoute
  HomeHomeIdRoomRoomIdRoute: typeof HomeHomeIdRoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/$homeId/': {
      id: '/home/$homeId/'
      path: '/home/$homeId'
      fullPath: '/home/$homeId/'
      preLoaderRoute: typeof HomeHomeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/$homeId/room/$roomId': {
      id: '/home/$homeId/room/$roomId'
      path: '/home/$homeId/room/$roomId'
      fullPath: '/home/$homeId/room/$roomId'
      preLoaderRoute: typeof HomeHomeIdRoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  HomeHomeIdIndexRoute: HomeHomeIdIndexRoute,
  HomeHomeIdRoomRoomIdRoute: HomeHomeIdRoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
